<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" xmi:id="EPackage6"
    name="SVG" nsURI="http://www.w3.org/Graphics/SVG/1.1/" nsPrefix="SVG">
  <eClassifiers xsi:type="ecore:EClass" xmi:id="EClass7" name="Element" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="EReference8" name="owner"
        ordered="false" upperBound="-1" eType="#EClass113" eOpposite="#EReference115"/>
    <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="EReference9" name="target"
        ordered="false" upperBound="-1" eType="#EClass35" eOpposite="#EReference36"/>
    <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="EReference10" name="attribute"
        ordered="false" upperBound="-1" eType="#EClass83" eOpposite="#EReference84"/>
    <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="EReference11" name="position"
        ordered="false" eType="#EClass105" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="EReference12" name="size"
        ordered="false" eType="#EClass102" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="EReference13" name="root"
        ordered="false" eType="#EClass23" eOpposite="#EReference25"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" xmi:id="EAttribute14" name="fill"
        ordered="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" xmi:id="EAttribute15" name="viewBox"
        ordered="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="EReference16" name="group"
        ordered="false" eType="#EClass29" eOpposite="#EReference30"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" xmi:id="EAttribute17" name="identifier"
        ordered="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="EReference18" name="drawsMarker"
        ordered="false" eType="#EClass68" eOpposite="#EReference75"/>
    <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="EReference19" name="metaData"
        ordered="false" lowerBound="1" eType="#EClass116" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" xmi:id="EClass20" name="StructuralElement"
      abstract="true" eSuperTypes="#EClass7"/>
  <eClassifiers xsi:type="ecore:EClass" xmi:id="EClass21" name="Image" eSuperTypes="#EClass20">
    <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="EReference22" name="referee"
        ordered="false" upperBound="-1" eType="#EClass110" eOpposite="#EReference111"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" xmi:id="EClass23" name="Svg" eSuperTypes="#EClass20">
    <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="EReference25" name="children"
        upperBound="-1" eType="#EClass7" containment="true" eOpposite="#EReference13"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" xmi:id="EAttribute26" name="namespace"
        ordered="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" xmi:id="EAttribute27" name="version"
        ordered="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" xmi:id="EAttribute28" name="baseProfile"
        ordered="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" xmi:id="EAttribute1" name="style"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="width" ordered="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="height" ordered="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" xmi:id="EClass29" name="GroupingElement" abstract="true"
      eSuperTypes="#EClass20">
    <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="EReference30" name="groupContent"
        upperBound="-1" eType="#EClass7" containment="true" eOpposite="#EReference16"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" xmi:id="EClass31" name="G" eSuperTypes="#EClass29">
    <eStructuralFeatures xsi:type="ecore:EAttribute" xmi:id="EAttribute32" name="name"
        ordered="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" xmi:id="EClass33" name="Defs" eSuperTypes="#EClass29"/>
  <eClassifiers xsi:type="ecore:EClass" xmi:id="EClass34" name="Symbol" eSuperTypes="#EClass29"/>
  <eClassifiers xsi:type="ecore:EClass" xmi:id="EClass35" name="Use" eSuperTypes="#EClass20">
    <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="EReference36" name="use"
        ordered="false" upperBound="-1" eType="#EClass7" eOpposite="#EReference9"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" xmi:id="EClass37" name="GraphicalElement"
      abstract="true" eSuperTypes="#EClass7">
    <eStructuralFeatures xsi:type="ecore:EAttribute" xmi:id="EAttribute38" name="stroke"
        ordered="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" xmi:id="EClass39" name="Shape" abstract="true"
      eSuperTypes="#EClass37"/>
  <eClassifiers xsi:type="ecore:EClass" xmi:id="EClass40" name="TextElement" abstract="true"
      eSuperTypes="#EClass37">
    <eStructuralFeatures xsi:type="ecore:EAttribute" xmi:id="EAttribute41" name="rotate"
        ordered="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" xmi:id="EAttribute42" name="textLength"
        ordered="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" xmi:id="EAttribute43" name="fontSize"
        ordered="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="textAlign" ordered="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" xmi:id="EClass44" name="Rect" eSuperTypes="#EClass39">
    <eStructuralFeatures xsi:type="ecore:EAttribute" xmi:id="EAttribute45" name="rx"
        ordered="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" xmi:id="EAttribute46" name="ry"
        ordered="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" xmi:id="EClass47" name="Circle" eSuperTypes="#EClass39"/>
  <eClassifiers xsi:type="ecore:EClass" xmi:id="EClass48" name="Ellipse" eSuperTypes="#EClass39"/>
  <eClassifiers xsi:type="ecore:EClass" xmi:id="EClass49" name="Line" eSuperTypes="#EClass39">
    <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="EReference50" name="between"
        ordered="false" lowerBound="2" upperBound="2" eType="#EClass67"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" xmi:id="EAttribute51" name="markerEnd"
        ordered="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" xmi:id="EAttribute52" name="markerStart"
        ordered="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" xmi:id="EClass53" name="Polyline" eSuperTypes="#EClass39">
    <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="EReference54" name="waypoints"
        upperBound="-1" eType="#EClass67" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" xmi:id="EAttribute55" name="strokeDashArray"
        ordered="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" xmi:id="EAttribute56" name="markerEnd"
        ordered="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" xmi:id="EAttribute57" name="markerStart"
        ordered="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" xmi:id="EClass58" name="Polygon" eSuperTypes="#EClass39">
    <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="EReference59" name="waypoints"
        upperBound="-1" eType="#EClass67"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" xmi:id="EAttribute60" name="markerEnd"
        ordered="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" xmi:id="EAttribute61" name="markerStart"
        ordered="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" xmi:id="EClass62" name="Path" eSuperTypes="#EClass39">
    <eStructuralFeatures xsi:type="ecore:EAttribute" xmi:id="EAttribute63" name="pathLength"
        ordered="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" xmi:id="EAttribute64" name="d"
        ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" xmi:id="EAttribute65" name="markerEnd"
        ordered="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" xmi:id="EAttribute66" name="markerStart"
        ordered="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" xmi:id="EClass67" name="Point" eSuperTypes="#EClass39"/>
  <eClassifiers xsi:type="ecore:EClass" xmi:id="EClass68" name="Marker" eSuperTypes="#EClass39">
    <eStructuralFeatures xsi:type="ecore:EAttribute" xmi:id="EAttribute69" name="markerUnits"
        ordered="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" xmi:id="EAttribute70" name="refX"
        ordered="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" xmi:id="EAttribute71" name="refY"
        ordered="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" xmi:id="EAttribute72" name="markerWidth"
        ordered="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" xmi:id="EAttribute73" name="markerHeight"
        ordered="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" xmi:id="EAttribute74" name="orient"
        ordered="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="EReference75" name="drawing"
        ordered="false" upperBound="-1" eType="#EClass7" containment="true" eOpposite="#EReference18"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" xmi:id="EClass76" name="Text" eSuperTypes="#EClass40">
    <eStructuralFeatures xsi:type="ecore:EAttribute" xmi:id="EAttribute77" name="lengthAdjust"
        ordered="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" xmi:id="EAttribute78" name="content"
        ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" xmi:id="EClass79" name="Tspan" eSuperTypes="#EClass40">
    <eStructuralFeatures xsi:type="ecore:EAttribute" xmi:id="EAttribute80" name="content"
        ordered="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" xmi:id="EClass81" name="Tref" eSuperTypes="#EClass40">
    <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="EReference82" name="xlinkHref"
        ordered="false" lowerBound="1" eType="#EClass40"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" xmi:id="EClass83" name="Attribute" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="EReference84" name="attOwner"
        ordered="false" upperBound="-1" eType="#EClass7" eOpposite="#EReference10"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" xmi:id="EClass85" name="Transform" abstract="true"
      eSuperTypes="#EClass83"/>
  <eClassifiers xsi:type="ecore:EClass" xmi:id="EClass86" name="Scale" eSuperTypes="#EClass85">
    <eStructuralFeatures xsi:type="ecore:EAttribute" xmi:id="EAttribute87" name="sx"
        ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" xmi:id="EAttribute88" name="sy"
        ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" xmi:id="EClass89" name="Translate" eSuperTypes="#EClass85">
    <eStructuralFeatures xsi:type="ecore:EAttribute" xmi:id="EAttribute90" name="tx"
        ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" xmi:id="EAttribute91" name="ty"
        ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" xmi:id="EClass92" name="Rotate" eSuperTypes="#EClass85">
    <eStructuralFeatures xsi:type="ecore:EAttribute" xmi:id="EAttribute93" name="angle"
        ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" xmi:id="EAttribute94" name="cx"
        ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" xmi:id="EAttribute95" name="cy"
        ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" xmi:id="EClass96" name="Visibility" eSuperTypes="#EClass83">
    <eStructuralFeatures xsi:type="ecore:EAttribute" xmi:id="EAttribute97" name="visible"
        ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" xmi:id="EClass98" name="FontWeight" eSuperTypes="#EClass83">
    <eStructuralFeatures xsi:type="ecore:EAttribute" xmi:id="EAttribute99" name="bold"
        ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" xmi:id="EClass100" name="FontStyle" eSuperTypes="#EClass83">
    <eStructuralFeatures xsi:type="ecore:EAttribute" xmi:id="EAttribute101" name="italic"
        ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" xmi:id="EClass102" name="Dimension">
    <eStructuralFeatures xsi:type="ecore:EAttribute" xmi:id="EAttribute103" name="width"
        ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" xmi:id="EAttribute104" name="height"
        ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" xmi:id="EClass105" name="Coordinates">
    <eStructuralFeatures xsi:type="ecore:EAttribute" xmi:id="EAttribute106" name="x"
        ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" xmi:id="EAttribute107" name="y"
        ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" xmi:id="EClass108" name="RelativeCoord" eSuperTypes="#EClass105"/>
  <eClassifiers xsi:type="ecore:EClass" xmi:id="EClass109" name="AbsoluteCoord" eSuperTypes="#EClass105"/>
  <eClassifiers xsi:type="ecore:EClass" xmi:id="EClass110" name="ReferencedFile" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="EReference111" name="referer"
        ordered="false" upperBound="-1" eType="#EClass21" eOpposite="#EReference22"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" xmi:id="EAttribute112" name="name"
        ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" xmi:id="EClass113" name="SvgFile" eSuperTypes="#EClass110">
    <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="EReference114" name="tag"
        ordered="false" lowerBound="1" eType="#EClass23"/>
    <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="EReference115" name="elements"
        ordered="false" upperBound="-1" eType="#EClass7" eOpposite="#EReference8"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" xmi:id="EClass116" name="MetaData">
    <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="EReference117" name="svgData"
        ordered="false" upperBound="-1" eType="#EClass118" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" xmi:id="EClass118" name="SVGData" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" xmi:id="EClass119" name="Precinct" eSuperTypes="#EClass118">
    <eStructuralFeatures xsi:type="ecore:EAttribute" xmi:id="EAttribute120" name="Number"
        ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" xmi:id="EAttribute121" name="Name"
        ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" xmi:id="EAttribute122" name="Location"
        ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="EReference123" name="candidates"
        ordered="false" upperBound="-1" eType="#EClass124" containment="true" eOpposite="#EReference2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" xmi:id="EClass124" name="Candidate">
    <eStructuralFeatures xsi:type="ecore:EAttribute" xmi:id="EAttribute125" name="Name"
        ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" xmi:id="EAttribute126" name="VotePercentage"
        ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="EReference2" name="precinct"
        eType="#EClass119" eOpposite="#EReference123"/>
  </eClassifiers>
</ecore:EPackage>
