<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="rwm"
    nsURI="http://www.bluexml.com/requirements/" nsPrefix="rwm">
  <eClassifiers xsi:type="ecore:EClass" name="ModelElement" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="BasicElement" abstract="true" eSuperTypes="#//ModelElement #//rwm_extended/StereotypedElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="documentation" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Entity" eSuperTypes="#//BasicElement #//rwm_geo/VisualElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" eType="#//Entity"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attributes" upperBound="-1"
        eType="#//Attribute" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RelationShip" eSuperTypes="#//BasicElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ends" upperBound="2" eType="#//End"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Attribute" eSuperTypes="#//BasicElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//AttributeType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="AttributeType">
    <eLiterals name="TextualValue"/>
    <eLiterals name="NumericalValue" value="1" literal="NumericalValue"/>
    <eLiterals name="TemporalValue" value="2" literal="TemporalValue"/>
    <eLiterals name="Other" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="End">
    <eStructuralFeatures xsi:type="ecore:EReference" name="object" lowerBound="1"
        eType="#//Entity"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="minCardinality" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxCardinality" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Organization" eSuperTypes="#//BasicElement #//rwm_geo/VisualElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="members" upperBound="-1"
        eType="#//Agent" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="goals" upperBound="-1"
        eType="#//Goal" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sub" upperBound="-1" eType="#//Organization"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="entities" upperBound="-1"
        eType="#//Entity" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="relations" upperBound="-1"
        eType="#//RelationShip" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Agent" eSuperTypes="#//BasicElement #//rwm_geo/VisualElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isHuman" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="isResponsible" upperBound="-1"
        eType="#//Goal" eOpposite="#//Goal/responsible"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Goal" eSuperTypes="#//BasicElement #//rwm_geo/VisualElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="subgoals" upperBound="-1"
        eType="#//Goal" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="priority" eType="#//PriorityLevel"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="responsible" upperBound="-1"
        eType="#//Agent" eOpposite="#//Agent/isResponsible"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="privilegeGroup" eType="#//PrivilegeGroup"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="PriorityLevel">
    <eLiterals name="VeryHigh"/>
    <eLiterals name="High" value="1"/>
    <eLiterals name="Normal"/>
    <eLiterals name="Low"/>
    <eLiterals name="VeryLow"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Privilege">
    <eStructuralFeatures xsi:type="ecore:EReference" name="element" lowerBound="1"
        eType="#//BasicElement"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="category" eType="#//PrivilegeNature"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="PrivilegeNature">
    <eLiterals name="create"/>
    <eLiterals name="read" value="1"/>
    <eLiterals name="update"/>
    <eLiterals name="delete"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RequirementsDefinition" eSuperTypes="#//Organization">
    <eStructuralFeatures xsi:type="ecore:EReference" name="stereotypes" upperBound="-1"
        eType="#//rwm_extended/Stereotype" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PrivilegeGroup">
    <eStructuralFeatures xsi:type="ecore:EReference" name="entryPoint" eType="#//Entity"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="privileges" upperBound="-1"
        eType="#//Privilege" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="documentation" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eSubpackages name="rwm_geo" nsURI="http://rwm/geo" nsPrefix="rwm_geo">
    <eClassifiers xsi:type="ecore:EClass" name="VisualElement" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="x" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="y" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="width" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="height" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="rwm_extended" nsURI="http://rwm/extended" nsPrefix="rwm_extended">
    <eClassifiers xsi:type="ecore:EClass" name="Stereotype">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="properties" upperBound="-1"
          eType="#//rwm_extended/Property" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Property">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="StereotypeInstanciation">
      <eStructuralFeatures xsi:type="ecore:EReference" name="def" lowerBound="1" eType="#//rwm_extended/Stereotype"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="properties" upperBound="-1"
          eType="#//rwm_extended/PropertyInstanciation" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PropertyInstanciation">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="def" lowerBound="1" eType="#//rwm_extended/Property"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="StereotypedElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="stereotypeInstanciation"
          upperBound="-1" eType="#//rwm_extended/StereotypeInstanciation" containment="true"/>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
