<?xml version="1.0" encoding="UTF-8"?>
<rwm:RequirementsDefinition xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:rwm="http://rwm" xmi:id="_TnQCYKb7Edyg0-Q2ek6f8g"
    name="MyRequirements">
  <members xmi:id="3igsd38yT0" name="Professionnel du tourisme" documentation="" x="727"
      y="32" width="48" height="70" isHuman="true" isResponsible="#PDFG4FIafJ #6gc1emEqKC #DLFCZQPDKZ #KbqC3JH29q"/>
  <goals xmi:id="PDFG4FIafJ" name="Supprimer un prospect" documentation="Suppression d’un prospect dans l’outil métier, après recherche en vue de faire un mailing.&lt;br>&lt;br>&lt;u>&lt;b>Pré-conditions :&lt;/b>&lt;/u> L’acteur doit être authentifié dans le système. L’acteur doit avoirpréalablement fait une recherche de prospects en vue de faire un mailing.&lt;br>"
      x="359" y="194" width="151" height="42" responsible="#3igsd38yT0">
    <subgoals xmi:id="R8gvz0NwcT" name="Sélection des prospects à supprimer" documentation="L’acteur sélectionne un ou plusieurs prospects dans la liste des résultats de recherche puis clique sur l’icône de suppression d’un prospect."
        x="122" y="375" width="157" height="54"/>
    <subgoals xmi:id="v0FO1HV6yp" name="Exécuter la suppression" documentation="Le système vérifie qu’au moins un prospect est sélectionné. Si ce n’est pas le cas, un message d’information est présenté à l’acteur et le système bloque le processus. Le système revient ensuite à la page des résultats de recherche."
        x="326" y="438" width="157" height="42"/>
    <privilegeGroup entryPoint="#EtUckvIUGQ" documentation="">
      <privileges element="#EtUckvIUGQ" category="read"/>
      <privileges element="#tepod8gzCU" category="read"/>
      <privileges element="#PlwbxWFn1B" category="read"/>
    </privilegeGroup>
  </goals>
  <goals xmi:id="6gc1emEqKC" name="Modifier un prospect" documentation="Modification d’un prospect dans l’outil métier, après association à une demande ou après recherche en vue de faire un mailing.&lt;br>&lt;br>&lt;b>Pré-conditions&lt;/b>&lt;br>&lt;br>L’acteur doit être authentifié dans le système.&lt;br>L’acteur doit avoirpréalablement (au choix) :&lt;br>&lt;ul>&lt;li>associé ce prospect à une demande, soit par la recherche, soit par la création.&lt;/li>&lt;/ul>&lt;ul>&lt;li>fait une recherche de prospects en vue de faire un mailing.&lt;/li>&lt;/ul>"
      x="614" y="187" width="140" height="42" responsible="#3igsd38yT0">
    <privilegeGroup entryPoint="#EtUckvIUGQ" documentation="Le système vérifie (RG-002) qu’au moins un des champs obligatoires est renseigné. Si ce n’est pas le cas, un message d’information est présenté à l’acteur et le système bloque le processus. Le système revient ensuite au formulaire de création de demande, en y associant automatiquement le prospect modifié.">
      <privileges element="#EtUckvIUGQ" category="read"/>
      <privileges element="#EtUckvIUGQ" category="update"/>
      <privileges element="#x4Q3TAHDCO" category="read"/>
      <privileges element="#x4Q3TAHDCO" category="update"/>
      <privileges element="#fktrcyPUTQ" category="read"/>
      <privileges element="#fktrcyPUTQ" category="update"/>
      <privileges element="#F1HlV6fEqr" category="read"/>
      <privileges element="#F1HlV6fEqr" category="update"/>
      <privileges element="#PMJBKguQkP" category="read"/>
      <privileges element="#PMJBKguQkP" category="update"/>
      <privileges element="#mMBTAO92t5" category="read"/>
      <privileges element="#mMBTAO92t5" category="update"/>
      <privileges element="#XroXIWTXMS" category="read"/>
      <privileges element="#XroXIWTXMS" category="update"/>
      <privileges element="#yxFGe89fhC" category="read"/>
      <privileges element="#yxFGe89fhC" category="update"/>
      <privileges element="#tepod8gzCU" category="read"/>
      <privileges element="#tepod8gzCU" category="update"/>
      <privileges element="#E907ddwNPo" category="read"/>
      <privileges element="#E907ddwNPo" category="update"/>
      <privileges element="#xq3arH7oTt" category="read"/>
      <privileges element="#xq3arH7oTt" category="update"/>
      <privileges element="#PlwbxWFn1B" category="read"/>
      <privileges element="#PlwbxWFn1B" category="update"/>
      <privileges element="#W8drnu7sIO" category="read"/>
      <privileges element="#W8drnu7sIO" category="update"/>
      <privileges element="#MZz0Ndd4eC" category="read"/>
      <privileges element="#MZz0Ndd4eC" category="update"/>
      <privileges element="#KOqdFIaOZn" category="read"/>
      <privileges element="#KOqdFIaOZn" category="update"/>
      <privileges element="#eyiRa54NGV" category="read"/>
      <privileges element="#eyiRa54NGV" category="update"/>
    </privilegeGroup>
  </goals>
  <goals xmi:id="DLFCZQPDKZ" name="Créer un prospect" documentation="Création d’un prospect dans l’outil métier, en vue de l’associer à une demande ou dans le contexte du mailing."
      x="866" y="189" width="128" height="42" responsible="#3igsd38yT0">
    <subgoals xmi:id="o3PZNQX9J2" name="Recherche d'un prospect" documentation="Pour éviter la création de prospect en doublon, l’acteur doit d’abord effectuer une recherche de prospects en se basant sur le nom par exemple. Cette recherche préalable est obligatoire dans le contexte d’une demande, optionnelle dans le contexte du mailing."
        x="856" y="361" width="162" height="42">
      <privilegeGroup entryPoint="#EtUckvIUGQ" documentation="">
        <privileges element="#EtUckvIUGQ" category="read"/>
        <privileges element="#tepod8gzCU" category="read"/>
      </privilegeGroup>
    </subgoals>
    <subgoals xmi:id="RFNM1uXS9f" name="Renseigner les informations nécessaires" documentation=""
        x="925" y="461" width="238" height="42">
      <privilegeGroup entryPoint="#EtUckvIUGQ" documentation="">
        <privileges element="#EtUckvIUGQ"/>
      </privilegeGroup>
    </subgoals>
  </goals>
  <goals xmi:id="KbqC3JH29q" name="Rechercher un prospect" documentation="Recherche d’un prospect dans l’outil métier, en vue de l’associer à une demande ou de faire un mailing.&lt;br>&lt;br>L’acteur doit obligatoirement renseigner (par saisie ou par choix dans une liste) un des critères proposés:&lt;br>&lt;ul>&lt;li>‘Raison sociale / nom / email’&lt;/li>&lt;li>‘Code postal’&lt;/li>&lt;li>‘Type’ (choix dans une liste)&lt;/li>&lt;/ul>"
      x="1075" y="177" width="157" height="42" responsible="#3igsd38yT0"/>
  <entities xmi:id="EtUckvIUGQ" name="Prospect" documentation="Les champs suivants sont obligatoires :&lt;br>‘Nom’ ou ‘Raison sociale’&lt;br>‘Code postal’&lt;br>‘Commune’&lt;br>&lt;br>&lt;i>Un utilitaire de recherche du code postal et de la commune est disponible dans ce formulaire. A partir de la saisie de deux caractères (au minimum) du code postal ou de la commune, une fenêtre complémentaire s’ouvre et propose la liste des communes concernées. Il est également possible, dans cette fenêtre, de modifier les critères de recherche. Un click sur un code postal ou le nom d’une commune, dans la liste des résultats, permet de renseigner directement les deux champs du formulaire ci-dessus avec les valeurs choisies.&lt;/i>&lt;br>"
      x="544" y="286" width="200" height="377">
    <attributes xmi:id="F1HlV6fEqr" name="civilite" documentation="Liste déroulante&lt;br>Valeur 'vide' disponible&lt;br>"/>
    <attributes xmi:id="tepod8gzCU" name="nom" documentation=""/>
    <attributes xmi:id="PlwbxWFn1B" name="prenom" documentation=""/>
    <attributes xmi:id="W8drnu7sIO" name="raison sociale" documentation=""/>
    <attributes xmi:id="KOqdFIaOZn" name="type de prospect" documentation="" type="Other"/>
    <attributes xmi:id="x4Q3TAHDCO" name="adresse" documentation="avec 3 champs de saisie&lt;br>"/>
    <attributes xmi:id="PMJBKguQkP" name="code postal" documentation="" type="NumericalValue"/>
    <attributes xmi:id="mMBTAO92t5" name="commune" documentation=""/>
    <attributes xmi:id="fktrcyPUTQ" name="cedex" documentation=""/>
    <attributes xmi:id="xq3arH7oTt" name="pays" documentation="Liste déroulante initialisée à France&lt;br>"
        type="Other"/>
    <attributes xmi:id="eyiRa54NGV" name="téléphone" documentation="avec 3 champs de saisie&lt;br>"/>
    <attributes xmi:id="yxFGe89fhC" name="fax" documentation=""/>
    <attributes xmi:id="XroXIWTXMS" name="e-mail" documentation=""/>
    <attributes xmi:id="MZz0Ndd4eC" name="sites web" documentation=""/>
    <attributes xmi:id="E907ddwNPo" name="observations" documentation="sur plusieurs lignes&lt;br>"/>
  </entities>
</rwm:RequirementsDefinition>
