<?xml version="1.0" encoding="UTF-8"?>
<rwm:RequirementsDefinition xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:rwm="http://rwm" xmi:id="_TnQCYKb7Edyg0-Q2ek6f8g"
    name="MyRequirements">
  <members xmi:id="Vrnpefayxa" name="Client distant" x="285" y="180" width="48" height="70"
      isHuman="true" isResponsible="#//@goals.0/@subgoals.1/@subgoals.0"/>
  <members xmi:id="h3mCXOzxf4" name="Bank Company" x="970" y="235" width="48" height="70"
      isHuman="true" isResponsible="#no0gz7HqIn"/>
  <members xmi:id="AdfSi4Ogah" name="Stock Management" x="790" y="240" width="48"
      height="70" isHuman="true" isResponsible="#ea1f1NwdOi"/>
  <members xmi:id="2cququ8ogC" name="Opérateur de stock" x="100" y="580" width="48"
      height="70" isHuman="true" isResponsible="#Air6DWRuMc"/>
  <goals xmi:id="LNC1a45DTR" name="Gestion du magasin" documentation="" x="40" y="25"
      width="137" height="42">
    <subgoals xmi:id="KL80Ko27tP" name="Maintenance" documentation="" x="20" y="260"
        width="102" height="42">
      <subgoals xmi:id="Air6DWRuMc" name="Mettre à jour le catalogue" documentation=""
          x="65" y="495" width="119" height="54" responsible="#2cququ8ogC"/>
      <subgoals xmi:id="fy4DGf33yn" name="Sécurité" documentation="" x="20" y="430"
          width="80" height="42"/>
      <subgoals xmi:id="sC0vpk8bCo" name="Surveillance du système" documentation=""
          x="155" y="430" width="99" height="54"/>
    </subgoals>
    <subgoals xmi:id="BU2xlG8h5I" name="Attirer de nouveaux clients" documentation=""
        x="245" y="110" width="169" height="42">
      <subgoals name="Faire du shopping" documentation="" x="440" y="180" width="127"
          height="42" responsible="#Vrnpefayxa">
        <subgoals xmi:id="eGG0L1lg7n" name="Faire une commande" documentation="" x="405"
            y="305" width="143" height="42">
          <subgoals xmi:id="3SAxmCAGV6" name="Sélectionner des items" documentation=""
              x="295" y="455" width="121" height="54">
            <subgoals xmi:id="ZM2urHNPTg" name="Sélectionner des items disponibles"
                documentation="" x="205" y="590" width="123" height="54"/>
            <subgoals xmi:id="XHAstv07s9" name="Pré-commander des items non disponibles"
                documentation="" x="365" y="590" width="119" height="66"/>
          </subgoals>
          <subgoals xmi:id="ndhMW4BK5C" name="Ajouter des items" documentation=""
              x="430" y="455" width="95" height="54"/>
          <subgoals xmi:id="FlpK2FSbrM" name="Valider la commande" documentation=""
              x="540" y="455" width="94" height="54"/>
          <subgoals xmi:id="QDpZvil4vs" name="Saisie des données d'identification"
              documentation="" x="645" y="455" width="107" height="66">
            <subgoals xmi:id="vDGq10c509" name="Saisie des informations bancaires"
                documentation="" x="585" y="590" width="152" height="54"/>
            <subgoals xmi:id="V2moWTohKV" name="Saisie des informations de livraison"
                documentation="" x="755" y="590" width="152" height="54"/>
          </subgoals>
        </subgoals>
        <subgoals xmi:id="ZfgXpeb8XT" name="Parcourir le catalogue" documentation=""
            x="580" y="305" width="146" height="42">
          <subgoals xmi:id="TXMF9BSeyv" name="Recherche par mots-clés" documentation=""
              x="795" y="400" width="113" height="54"/>
          <subgoals xmi:id="TzzhOogidT" name="Naviguer dans les catégories" documentation=""
              x="925" y="400" width="111" height="54"/>
        </subgoals>
      </subgoals>
      <subgoals xmi:id="ea1f1NwdOi" name="Assurer la livraison" documentation="" x="780"
          y="180" width="133" height="42" responsible="#AdfSi4Ogah"/>
      <subgoals xmi:id="no0gz7HqIn" name="Assurer le paiement" documentation="" x="965"
          y="180" width="137" height="42" responsible="#h3mCXOzxf4"/>
    </subgoals>
    <subgoals xmi:id="tBlV7l2IEJ" name="Faire des statistiques" documentation="" x="135"
        y="110" width="95" height="54">
      <subgoals xmi:id="6uLHL8WDBI" name="Isoler les nouveaux besoins" documentation=""
          x="135" y="220" width="129" height="54"/>
    </subgoals>
  </goals>
</rwm:RequirementsDefinition>
