package com.bluexml.side.util.generator.alfresco;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Properties;

import org.eclipse.core.resources.IFile;
import org.eclipse.core.resources.IFolder;

import com.bluexml.side.util.generator.packager.AbstractPackager;
import com.bluexml.side.util.libs.FileHelper;
import com.bluexml.side.util.libs.IFileHelper;
import com.bluexml.side.util.libs.zip.ZipManager;

public class AmpPackager extends AbstractPackager {
	private static String alfrescoModuleComment = "generated by S-IDE Alfresco Generator";
	private Map<String, File> mapper;

	public AmpPackager(IFolder folder, Properties moduleProperties, String technoV) {
		super(folder, moduleProperties, technoV);
		mapper = createAMPSkelleton();
	}

	public IFile buildPackage(boolean doClean) throws Exception {
		List<IFile> generatedFiles = IFileHelper.getAllFiles(IworkingDir);

		dispatchFiles(generatedFiles, mapper);
		buildModuleProperties();
		File ampFile = getPackageFile();
		ampFile.createNewFile();
		ZipManager.zip(getFolderToPackage(), ampFile, false);
		if (doClean) {
			FileHelper.deleteFile(getWorkingFolder());
		}
		IFile ampIFile = getPackageIFile();
		return ampIFile;
	}

	@Override
	protected String getPackageFileName() {
		return "module." + moduleProperties.getProperty("module.id") + ".amp";
	}

	@Override
	protected File getFolderToPackage() {
		return new File(getWorkingdir() + File.separator + "AMP");
	}

	private void dispatchFiles(List<IFile> files, Map<String, File> mapper) throws IOException {
		for (IFile f : files) {
			for (Map.Entry<String, File> ent : mapper.entrySet()) {
				if (IFileHelper.convertIRessourceToFile(f).getAbsolutePath().indexOf(ent.getKey()) != -1) {
					String path = f.getFullPath().makeAbsolute().toOSString();
					String pathIn = ent.getValue().getAbsolutePath() + File.separator + path.substring(path.indexOf(ent.getKey()) + ent.getKey().length());
					File dest = new File(pathIn);
					// put to this dir
					FileHelper.copyFiles(IFileHelper.convertIRessourceToFile(f), dest, true);
				}
			}
		}
	}

	private void buildModuleProperties() throws FileNotFoundException, IOException {
		File modulePropertiesfile = new File(getFolderToPackage().getAbsolutePath() + File.separator + "module.properties");
		moduleProperties.store(new FileOutputStream(modulePropertiesfile), alfrescoModuleComment);
	}

	/**
	 * Use to map generated filePath to corresponding AMP directory
	 * 
	 * @return
	 */
	private Map<String, File> createAMPSkelleton() {
		File ampRoot = getWorkingFolder();
		Map<String, File> mapper = new HashMap<String, File>();

		addToMap(mapper, "/alfresco/WEB-INF/classes/", ampRoot, "/config");
		addToMap(mapper, "/config/", ampRoot, "/config/");
		addToMap(mapper, "/alfresco/lib/", ampRoot, "/lib");
		addToMap(mapper, "/licences/", ampRoot, "/licences");
		addToMap(mapper, "/alfresco/jsp/", ampRoot, "/web/jsp");
		addToMap(mapper, "/alfresco/css/", ampRoot, "/web/css");
		addToMap(mapper, "/alfresco/images/", ampRoot, "/web/images");
		addToMap(mapper, "/alfresco/scripts/", ampRoot, "/web/scripts");

		return mapper;
	}

	private void addToMap(Map<String, File> map, String key, File ampRoot, String target) {
		map.put(key.replace("/", File.separator), createAndRegisterDir(ampRoot, target.replace("/", File.separator)));
	}

	private File createAndRegisterDir(File ampRoot, String p) {
		File dir = new File(getFolderToPackage().getAbsolutePath() + p);
		dir.mkdirs();
		return dir;
	}

}
