//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.01.15 at 02:53:18 PM CET 
//


package com.bluexml.xforms.controller.binding;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for fileFieldType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="fileFieldType">
 *   &lt;complexContent>
 *     &lt;extension base="{}formFieldType">
 *       &lt;sequence>
 *         &lt;element name="inRepository" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "fileFieldType", propOrder = {
    "inRepository"
})
public class FileFieldType
    extends FormFieldType
{

    protected boolean inRepository;

    /**
     * Gets the value of the inRepository property.
     * 
     */
    public boolean isInRepository() {
        return inRepository;
    }

    /**
     * Sets the value of the inRepository property.
     * 
     */
    public void setInRepository(boolean value) {
        this.inRepository = value;
    }

}
