<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="workflow"
    nsURI="http://www.kerblue.org/workflow/1.0" nsPrefix="workflow">
  <eClassifiers xsi:type="ecore:EClass" name="WorkflowModelElement" abstract="true"
      eSuperTypes="../../com.bluexml.side.Common/model/Common.ecore#//ModelElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="Process" eSuperTypes="../../com.bluexml.side.Common/model/Common.ecore#//Package">
    <eAnnotations source="http://www.bluexml.com/OCL">
      <details key="PackageNameNull" value="not self.name.oclIsUndefined() and self.name &lt;> ''"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="PackageNameNull"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="swimlane" upperBound="-1"
        eType="#//Swimlane" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="startstate" ordered="false"
        lowerBound="1" eType="#//StartState" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="endstate" lowerBound="1"
        upperBound="-1" eType="#//EndState" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="node" upperBound="-1" eType="#//Node"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tasknode" upperBound="-1"
        eType="#//TaskNode" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="processstate" upperBound="-1"
        eType="#//ProcessState" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fork" upperBound="-1" eType="#//Fork"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="join" upperBound="-1" eType="#//Join"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="decision" upperBound="-1"
        eType="#//Decision" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elements" upperBound="-1"
        eType="#//WorkflowModelElement" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="contentType" lowerBound="1"
        eType="ecore:EClass ../../com.bluexml.side.Class/model/Class.ecore#//Clazz"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Swimlane">
    <eAnnotations source="http://www.bluexml.com/OCL">
      <details key="ActorNameMustBeUnique" value="Swimlane.allInstances() -> select(n|n.name = self.name and n &lt;> self )->size()=0"/>
      <details key="MustManageAtLeastOneTask" value="not self.manage->isEmpty()"/>
      <details key="noSpecialCharacters" value="self.name.regexMatch('[\w]*') &lt;> null"/>
      <details key="OnlyOneActorCalledInitiator" value="Swimlane.allInstances() -> select(s| s.name ='initiator')->size() = 1"/>
      <details key="ActoridOrPooledactorMustBeSetForAllExeptOneActor" value="Swimlane.allInstances() -> select(s | s.name &lt;>'initiator' and (s.actorid -> isEmpty() or s.actorid='')  and (s.pooledactors  -> isEmpty() or s.pooledactors =''))->size() &lt;=1&#xA;"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="ActorNameMustBeUnique MustManageAtLeastOneTask noSpecialCharacters OnlyOneActorCalledInitiator ActoridOrPooledactorMustBeSetForAllExeptOneActor"/>
    </eAnnotations>
    <eOperations name="EqualsForMerge" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eAnnotations source="http://www.bluexml.com/OCL">
        <details key="body" value="self.name = other.name"/>
      </eAnnotations>
      <eParameters name="other" eType="#//Swimlane"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="manage" upperBound="-1"
        eType="#//TaskNode" eOpposite="#//TaskNode/swimlane"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="actorid" ordered="false"
        unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pooledactors" ordered="false"
        unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="clazz" ordered="false"
        unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StartState" eSuperTypes="#//State">
    <eAnnotations source="http://www.bluexml.com/OCL">
      <details key="OneStartTask" value="StartState.allInstances() -> size() = 1"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="OneStartTask"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="transition" upperBound="-1"
        eType="#//Transition" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="event" upperBound="-1"
        eType="#//Event" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="assignmentType" eType="#//BPMAssignmentType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="initiator" lowerBound="1"
        eType="#//Swimlane"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attributes" upperBound="-1"
        eType="#//Attribute" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="clazz" upperBound="-1"
        eType="ecore:EClass ../../com.bluexml.side.Class/model/Class.ecore#//Clazz"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EndState" eSuperTypes="#//State">
    <eAnnotations source="http://www.bluexml.com/OCL">
      <details key="atLeastOneEndTask" value="EndState.allInstances() -> size() = 1"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="atLeastOneEndTask"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="event" upperBound="-1"
        eType="#//Event" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Node" eSuperTypes="#//State">
    <eStructuralFeatures xsi:type="ecore:EReference" name="action" ordered="false"
        eType="#//Action" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="transition" upperBound="-1"
        eType="#//Transition" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="event" upperBound="-1"
        eType="#//Event" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TaskNode" eSuperTypes="#//State">
    <eAnnotations source="http://www.bluexml.com/OCL">
      <details key="TaskMustBePointerByTransition" value="Transition.allInstances()-> select(t| t.to = self)->size()=1 or self.transition -> notEmpty()&#xA;"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="NoTaskWithSameName TaskMustBePointerByTransition"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="transition" upperBound="-1"
        eType="#//Transition" containment="true" eOpposite="#//Transition/parentTaskNode"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="event" upperBound="-1"
        eType="#//Event" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="timer" upperBound="-1"
        eType="#//Timer" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="swimlane" ordered="false"
        lowerBound="1" eType="#//Swimlane" eOpposite="#//Swimlane/manage"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attributes" upperBound="-1"
        eType="#//Attribute" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="clazz" upperBound="-1"
        eType="ecore:EClass ../../com.bluexml.side.Class/model/Class.ecore#//Clazz"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProcessState" eSuperTypes="#//State">
    <eStructuralFeatures xsi:type="ecore:EReference" name="subprocess" ordered="false"
        lowerBound="1" eType="#//Process"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="transition" upperBound="-1"
        eType="#//Transition" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="event" upperBound="-1"
        eType="#//Event" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Fork" eSuperTypes="#//State">
    <eStructuralFeatures xsi:type="ecore:EReference" name="transition" upperBound="-1"
        eType="#//Transition" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="event" upperBound="-1"
        eType="#//Event" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Join" eSuperTypes="#//State">
    <eStructuralFeatures xsi:type="ecore:EReference" name="transition" upperBound="-1"
        eType="#//Transition" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="event" upperBound="-1"
        eType="#//Event" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Decision" eSuperTypes="#//State">
    <eStructuralFeatures xsi:type="ecore:EReference" name="transition" upperBound="-1"
        eType="#//Transition" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="event" upperBound="-1"
        eType="#//Event" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Event">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" ordered="false" unique="false"
        lowerBound="1" eType="#//BPMEventType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="action" upperBound="-1"
        eType="#//Action" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Action" eSuperTypes="#//WorkflowModelElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="javaClass" ordered="false"
        unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="expression" ordered="false"
        unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="script" ordered="false"
        upperBound="-1" eType="#//Script" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Script">
    <eStructuralFeatures xsi:type="ecore:EReference" name="variable" upperBound="-1"
        eType="#//Variable" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="expression" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Timer" eSuperTypes="#//Action">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="duedate" ordered="false"
        unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Variable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="access" ordered="false"
        unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Transition">
    <eAnnotations source="http://www.bluexml.com/OCL">
      <details key="NoTransitionWithSameName" value="Transition.allInstances() -> select(n|n.name = self.name and n &lt;> self )->size()=0"/>
      <details key="SourceAndTargetMustBeSet" value="not self.to.oclIsUndefined() and not self.getContainer().oclIsUndefined()"/>
      <details key="noSpecialCharacters" value="self.name.regexMatch('[\w]*') &lt;> null"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="NoTransitionWithSameName SourceAndTargetMustBeSet noSpecialCharacters"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="condition" ordered="false"
        unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="action" upperBound="-1"
        eType="#//Action" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parentTaskNode" ordered="false"
        eType="#//TaskNode" eOpposite="#//TaskNode/transition"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="timer" upperBound="-1"
        eType="#//Timer" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="to" lowerBound="1" eType="#//State"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="title" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="BPMEventType">
    <eLiterals name="task_create" literal="task-create"/>
    <eLiterals name="task_start" value="1" literal="task-start"/>
    <eLiterals name="task_assign" value="2" literal="task-assign"/>
    <eLiterals name="task_end" value="3" literal="task-end"/>
    <eLiterals name="node_enter" value="4" literal="node-enter"/>
    <eLiterals name="node_leave" value="5" literal="node-leave"/>
    <eLiterals name="before_signal" value="6" literal="before-signal"/>
    <eLiterals name="after_signal" value="7" literal="after-signal"/>
    <eLiterals name="superstate_enter" value="8" literal="superstate-enter"/>
    <eLiterals name="superstate_leave" value="9" literal="superstate-leave"/>
    <eLiterals name="transition" value="10" literal="transition"/>
    <eLiterals name="timer" value="11"/>
    <eLiterals name="subprocess_created" value="12" literal="subprocess-created"/>
    <eLiterals name="subprocess_end" value="13" literal="subprocess-end"/>
    <eLiterals name="process_start" value="14" literal="process-start"/>
    <eLiterals name="process_end" value="15" literal="process-end"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="State" abstract="true">
    <eAnnotations source="http://www.bluexml.com/OCL">
      <details key="noSpecialCharacters" value="self.name.regexMatch('[\w]*') &lt;> null"/>
      <details key="NoStateWithSameName" value="State.allInstances() -> select(n|n.name = self.name and n &lt;> self )->size()=0"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="NoStateWithSameName noSpecialCharacters"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="BPMAssignmentType">
    <eLiterals name="One_user" literal="One user"/>
    <eLiterals name="One_group" value="2" literal="One group"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Attribute">
    <eAnnotations source="http://www.bluexml.com/OCL">
      <details key="UniqueNameForTaskAttribute" value="Attribute.allInstances() -> select(n|n.name = self.name and n &lt;> self )->size()=0"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="UniqueNameForTaskAttribute"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="typ" eType="ecore:EEnum ../../com.bluexml.side.Class/model/Class.ecore#//AttributeType"
        defaultValueLiteral="void"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="title" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
