<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="workflow"
    nsURI="http://www.kerblue.org/workflow/1.0" nsPrefix="workflow">
  <eClassifiers xsi:type="ecore:EClass" name="WorkflowModelElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="Process" eSuperTypes="../../com.bluexml.side.Common/model/Common.ecore#//Package">
    <eStructuralFeatures xsi:type="ecore:EReference" name="swimlane" upperBound="-1"
        eType="#//Swimlane" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="startstate" ordered="false"
        eType="#//StartState" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="endstate" upperBound="-1"
        eType="#//EndState" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="node" upperBound="-1" eType="#//Node"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tasknode" upperBound="-1"
        eType="#//TaskNode" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="processstate" upperBound="-1"
        eType="#//ProcessState" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fork" upperBound="-1" eType="#//Fork"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="join" upperBound="-1" eType="#//Join"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="decision" upperBound="-1"
        eType="#//Decision" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Swimlane">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="manage" upperBound="-1"
        eType="#//TaskNode" eOpposite="#//TaskNode/swimlane"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="actorid" ordered="false"
        unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pooledactors" ordered="false"
        unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="clazz" ordered="false"
        unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StartState" eSuperTypes="#//State">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="transition" upperBound="-1"
        eType="#//Transition" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="event" upperBound="-1"
        eType="#//Event" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="assignmentType" eType="#//BPMAssignmentType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EndState" eSuperTypes="#//State">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="event" upperBound="-1"
        eType="#//Event" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Node" eSuperTypes="#//State">
    <eStructuralFeatures xsi:type="ecore:EReference" name="action" ordered="false"
        lowerBound="1" eType="#//Action" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="transition" upperBound="-1"
        eType="#//Transition" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="event" upperBound="-1"
        eType="#//Event" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TaskNode" eSuperTypes="#//State">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="transition" upperBound="-1"
        eType="#//Transition" containment="true" eOpposite="#//Transition/parentTaskNode"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="event" upperBound="-1"
        eType="#//Event" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="timer" upperBound="-1"
        eType="#//Timer" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="swimlane" ordered="false"
        lowerBound="1" eType="#//Swimlane" eOpposite="#//Swimlane/manage"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProcessState">
    <eStructuralFeatures xsi:type="ecore:EReference" name="subprocess" ordered="false"
        lowerBound="1" eType="#//Process"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="variable" upperBound="-1"
        eType="#//Variable" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Fork" eSuperTypes="#//State">
    <eStructuralFeatures xsi:type="ecore:EReference" name="transition" upperBound="-1"
        eType="#//Transition" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="event" upperBound="-1"
        eType="#//Event" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Join" eSuperTypes="#//State">
    <eStructuralFeatures xsi:type="ecore:EReference" name="transition" upperBound="-1"
        eType="#//Transition" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="event" upperBound="-1"
        eType="#//Event" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Decision" eSuperTypes="#//State">
    <eStructuralFeatures xsi:type="ecore:EReference" name="transition" upperBound="-1"
        eType="#//Transition" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="event" upperBound="-1"
        eType="#//Event" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Event">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" ordered="false" unique="false"
        lowerBound="1" eType="#//BPMEventType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="action" upperBound="-1"
        eType="#//Action" containment="true" eOpposite="#//Action/parentEvent"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Action">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="javaClass" ordered="false"
        unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="expression" ordered="false"
        unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="script" ordered="false"
        upperBound="-1" eType="#//Script" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parentEvent" ordered="false"
        eType="#//Event" eOpposite="#//Event/action"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parentTimer" ordered="false"
        eType="#//Timer" eOpposite="#//Timer/action"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Script">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="variable" upperBound="-1"
        eType="#//Variable" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="expression" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Timer">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="duedate" ordered="false"
        unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="action" ordered="false"
        lowerBound="1" eType="#//Action" containment="true" eOpposite="#//Action/parentTimer"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Variable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="access" ordered="false"
        unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Transition">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="condition" ordered="false"
        unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="action" upperBound="-1"
        eType="#//Action" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parentTaskNode" ordered="false"
        eType="#//TaskNode" eOpposite="#//TaskNode/transition"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="timer" upperBound="-1"
        eType="#//Timer" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="to" lowerBound="1" eType="#//State"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="title" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="BPMEventType">
    <eLiterals name="task_create" literal="task-create"/>
    <eLiterals name="task_start" value="1" literal="task-start"/>
    <eLiterals name="task_assign" value="2" literal="task-assign"/>
    <eLiterals name="task_end" value="3" literal="task-end"/>
    <eLiterals name="node_enter" value="4" literal="node-enter"/>
    <eLiterals name="node_leave" value="5" literal="node-leave"/>
    <eLiterals name="before_signal" value="6" literal="before-signal"/>
    <eLiterals name="after_signal" value="7" literal="after-signal"/>
    <eLiterals name="superstate_enter" value="8" literal="superstate-enter"/>
    <eLiterals name="superstate_leave" value="9" literal="superstate-leave"/>
    <eLiterals name="transition" value="10" literal="transition"/>
    <eLiterals name="timer" value="11"/>
    <eLiterals name="subprocess_created" value="12" literal="subprocess-created"/>
    <eLiterals name="subprocess_end" value="13" literal="subprocess-end"/>
    <eLiterals name="process_start" value="14" literal="process-start"/>
    <eLiterals name="process_end" value="15" literal="process-end"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="State" abstract="true"/>
  <eClassifiers xsi:type="ecore:EEnum" name="BPMAssignmentType">
    <eLiterals name="One_user" literal="One user"/>
    <eLiterals name="One_group" value="2" literal="One group"/>
  </eClassifiers>
</ecore:EPackage>
