<?xml version="1.0" encoding="ISO-8859-1"?>
<WebSite:Project xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:WebSite="http://www.bluexml.com/rwm/website/1.0/" name="My Web Project">
  <pages xsi:type="WebSite:LoginPage" name="index.html" title="List of users">
    <links label="Assistante" page="//@pages.2"/>
    <links label="Télé conseiller" page="//@pages.4"/>
    <links label="Analyste" page="//@pages.6"/>
    <links label="Administrateur" page="//@pages.8"/>
    <links label="Commercial" page="//@pages.10"/>
  </pages>
  <pages xsi:type="WebSite:FramePage" name="frame_bhxkQIbVyT.html" title="My Web Project"
      col1="//@pages.2"/>
  <pages xsi:type="WebSite:GoalPage" name="bhxkQIbVyT.html" title="Goals of Assistante">
    <items label="Saisir les informations" page="//@pages.15"/>
  </pages>
  <pages xsi:type="WebSite:FramePage" name="frame_ns5HgIOorM.html" title="My Web Project"
      col1="//@pages.4"/>
  <pages xsi:type="WebSite:GoalPage" name="ns5HgIOorM.html" title="Goals of Télé conseiller">
    <items label="Mettre à jour les informations" page="//@pages.11"/>
  </pages>
  <pages xsi:type="WebSite:FramePage" name="frame_2U7KFEpZh6.html" title="My Web Project"
      col1="//@pages.6"/>
  <pages xsi:type="WebSite:GoalPage" name="2U7KFEpZh6.html" title="Goals of Analyste">
    <items label="Analyser les informations" page="//@pages.13"/>
  </pages>
  <pages xsi:type="WebSite:FramePage" name="frame_o14LzByM3t.html" title="My Web Project"
      col1="//@pages.8"/>
  <pages xsi:type="WebSite:GoalPage" name="o14LzByM3t.html" title="Goals of Administrateur">
    <items label="Administrer les informations" page="//@pages.12"/>
  </pages>
  <pages xsi:type="WebSite:FramePage" name="frame_A4RyC0lg0U.html" title="My Web Project"
      col1="//@pages.10"/>
  <pages xsi:type="WebSite:GoalPage" name="A4RyC0lg0U.html" title="Goals of Commercial">
    <items label="Consulter les informations" page="//@pages.14"/>
  </pages>
  <pages xsi:type="WebSite:DataPage" name="PyNiT9GOWR.php" title="Mettre à jour les informations"
      mainComponent="//@pages.11/@components.0">
    <components name="Répertoire" canRead="true" canUpdate="true" table="//@schema/@tables.1">
      <properties xsi:type="WebSite:ComponentAttribute" name="nom" canRead="true"
          canUpdate="true" field="//@schema/@tables.1/@fields.1"/>
    </components>
    <components name="Fiche" canRead="true" canUpdate="true" table="//@schema/@tables.2">
      <properties xsi:type="WebSite:ComponentAttribute" name="nom" canRead="true"
          canUpdate="true" field="//@schema/@tables.2/@fields.1"/>
      <properties xsi:type="WebSite:ComponentAttribute" name="prénom" canRead="true"
          canUpdate="true" field="//@schema/@tables.2/@fields.2"/>
      <properties xsi:type="WebSite:ComponentAttribute" name="adresse" canRead="true"
          canUpdate="true" field="//@schema/@tables.2/@fields.3"/>
      <properties xsi:type="WebSite:ComponentAttribute" name="code postal" canRead="true"
          canUpdate="true" field="//@schema/@tables.2/@fields.4"/>
      <properties xsi:type="WebSite:ComponentAttribute" name="ville" canRead="true"
          canUpdate="true" field="//@schema/@tables.2/@fields.5"/>
      <properties xsi:type="WebSite:ComponentAttribute" name="téléphone" canRead="true"
          canUpdate="true" field="//@schema/@tables.2/@fields.6"/>
      <properties xsi:type="WebSite:ComponentAttribute" name="portable" canRead="true"
          canUpdate="true" field="//@schema/@tables.2/@fields.7"/>
    </components>
  </pages>
  <pages xsi:type="WebSite:DataPage" name="nwEB8IhcRP.php" title="Administrer les informations"
      mainComponent="//@pages.12/@components.0">
    <components name="Carnet d'adresse" canCreate="true" canRead="true" canUpdate="true"
        table="//@schema/@tables.0">
      <properties xsi:type="WebSite:ComponentRelationShip" name="contient" canRead="true"
          canUpdate="true" idLeft="//@schema/@tables.1/@fields.0" idRight="//@schema/@tables.0/@fields.0"
          mandatoryLeft="true"/>
    </components>
    <components name="Répertoire" canCreate="true" canRead="true" canUpdate="true"
        table="//@schema/@tables.1">
      <properties xsi:type="WebSite:ComponentAttribute" name="nom" canRead="true"
          canUpdate="true" field="//@schema/@tables.1/@fields.1"/>
      <properties xsi:type="WebSite:ComponentRelationShip" name="contient" canRead="true"
          canUpdate="true" idLeft="//@schema/@tables.1/@fields.0" idRight="//@schema/@tables.0/@fields.0"
          mandatoryLeft="true"/>
      <properties xsi:type="WebSite:ComponentRelationShip" name="fiches" canRead="true"
          canUpdate="true" idLeft="//@schema/@tables.2/@fields.0" idRight="//@schema/@tables.1/@fields.0"
          mandatoryLeft="true"/>
    </components>
    <components name="Fiche" canRead="true" table="//@schema/@tables.2">
      <properties xsi:type="WebSite:ComponentAttribute" name="nom" canRead="true"
          field="//@schema/@tables.2/@fields.1"/>
      <properties xsi:type="WebSite:ComponentAttribute" name="prénom" canRead="true"
          field="//@schema/@tables.2/@fields.2"/>
      <properties xsi:type="WebSite:ComponentAttribute" name="adresse" canRead="true"
          field="//@schema/@tables.2/@fields.3"/>
      <properties xsi:type="WebSite:ComponentAttribute" name="code postal" canRead="true"
          field="//@schema/@tables.2/@fields.4"/>
      <properties xsi:type="WebSite:ComponentAttribute" name="ville" canRead="true"
          field="//@schema/@tables.2/@fields.5"/>
      <properties xsi:type="WebSite:ComponentAttribute" name="téléphone" canRead="true"
          field="//@schema/@tables.2/@fields.6"/>
      <properties xsi:type="WebSite:ComponentAttribute" name="portable" canRead="true"
          field="//@schema/@tables.2/@fields.7"/>
      <properties xsi:type="WebSite:ComponentRelationShip" name="fiches" canRead="true"
          canUpdate="true" idLeft="//@schema/@tables.2/@fields.0" idRight="//@schema/@tables.1/@fields.0"
          mandatoryLeft="true"/>
    </components>
  </pages>
  <pages xsi:type="WebSite:DataPage" name="DTdwz9LcOn.php" title="Analyser les informations"
      mainComponent="//@pages.13/@components.0">
    <components name="Fiche" canRead="true" table="//@schema/@tables.2">
      <properties xsi:type="WebSite:ComponentAttribute" name="code postal" canRead="true"
          field="//@schema/@tables.2/@fields.4"/>
      <properties xsi:type="WebSite:ComponentAttribute" name="ville" canRead="true"
          field="//@schema/@tables.2/@fields.5"/>
    </components>
  </pages>
  <pages xsi:type="WebSite:DataPage" name="dcp3FSTMOz.php" title="Consulter les informations"
      mainComponent="//@pages.14/@components.0">
    <components name="Fiche" canRead="true" table="//@schema/@tables.2">
      <properties xsi:type="WebSite:ComponentAttribute" name="nom" canRead="true"
          field="//@schema/@tables.2/@fields.1"/>
      <properties xsi:type="WebSite:ComponentAttribute" name="prénom" canRead="true"
          field="//@schema/@tables.2/@fields.2"/>
      <properties xsi:type="WebSite:ComponentAttribute" name="adresse" canRead="true"
          field="//@schema/@tables.2/@fields.3"/>
      <properties xsi:type="WebSite:ComponentAttribute" name="code postal" canRead="true"
          field="//@schema/@tables.2/@fields.4"/>
      <properties xsi:type="WebSite:ComponentAttribute" name="ville" canRead="true"
          field="//@schema/@tables.2/@fields.5"/>
      <properties xsi:type="WebSite:ComponentAttribute" name="téléphone" canRead="true"
          field="//@schema/@tables.2/@fields.6"/>
      <properties xsi:type="WebSite:ComponentAttribute" name="portable" canRead="true"
          field="//@schema/@tables.2/@fields.7"/>
    </components>
  </pages>
  <pages xsi:type="WebSite:DataPage" name="bUa55Oe2Bt.php" title="Saisir les informations"
      mainComponent="//@pages.15/@components.0">
    <components name="Fiche" canCreate="true" canRead="true" canUpdate="true" canDelete="true"
        table="//@schema/@tables.2">
      <properties xsi:type="WebSite:ComponentAttribute" name="nom" canRead="true"
          canUpdate="true" field="//@schema/@tables.2/@fields.1"/>
      <properties xsi:type="WebSite:ComponentAttribute" name="prénom" canRead="true"
          canUpdate="true" field="//@schema/@tables.2/@fields.2"/>
      <properties xsi:type="WebSite:ComponentAttribute" name="adresse" canRead="true"
          canUpdate="true" field="//@schema/@tables.2/@fields.3"/>
      <properties xsi:type="WebSite:ComponentAttribute" name="code postal" canUpdate="true"
          field="//@schema/@tables.2/@fields.4"/>
      <properties xsi:type="WebSite:ComponentAttribute" name="ville" canRead="true"
          canUpdate="true" field="//@schema/@tables.2/@fields.5"/>
      <properties xsi:type="WebSite:ComponentAttribute" name="téléphone" canRead="true"
          canUpdate="true" field="//@schema/@tables.2/@fields.6"/>
      <properties xsi:type="WebSite:ComponentAttribute" name="portable" canRead="true"
          canUpdate="true" field="//@schema/@tables.2/@fields.7"/>
      <properties xsi:type="WebSite:ComponentRelationShip" name="fiches" canUpdate="true"
          idLeft="//@schema/@tables.2/@fields.0" idRight="//@schema/@tables.1/@fields.0"
          mandatoryLeft="true"/>
    </components>
    <components name="Répertoire" canRead="true" table="//@schema/@tables.1">
      <properties xsi:type="WebSite:ComponentAttribute" name="nom" canRead="true"
          field="//@schema/@tables.1/@fields.1"/>
      <properties xsi:type="WebSite:ComponentRelationShip" name="fiches" canUpdate="true"
          idLeft="//@schema/@tables.2/@fields.0" idRight="//@schema/@tables.1/@fields.0"
          mandatoryLeft="true"/>
    </components>
  </pages>
  <pages xsi:type="WebSite:GoalPage" name="ooQGkFIbGp.html" title="Gestion de carnet d'adresses">
    <items label="Gestion de carnet d'adresses" page="//@pages.16">
      <sub label="Mettre à jour les informations" page="//@pages.11"/>
      <sub label="Administrer les informations" page="//@pages.12"/>
      <sub label="Analyser les informations" page="//@pages.13"/>
      <sub label="Consulter les informations" page="//@pages.14"/>
      <sub label="Saisir les informations" page="//@pages.15"/>
    </items>
  </pages>
  <schema>
    <tables name="Carnetdadresse" primaryKey="//@schema/@tables.0/@fields.0">
      <fields name="id_MGR7Rpm4rz" dataType="integer" autoincrement="true"/>
    </tables>
    <tables name="Rpertoire" primaryKey="//@schema/@tables.1/@fields.0">
      <fields name="id_fp94N3ubdV" dataType="integer" autoincrement="true"/>
      <fields name="nom"/>
    </tables>
    <tables name="Fiche" primaryKey="//@schema/@tables.2/@fields.0">
      <fields name="id_nOXU6aUquV" dataType="integer" autoincrement="true"/>
      <fields name="nom"/>
      <fields name="prnom"/>
      <fields name="adresse"/>
      <fields name="codepostal"/>
      <fields name="ville"/>
      <fields name="tlphone" dataType="real"/>
      <fields name="portable" dataType="real"/>
    </tables>
    <tables name="Rpertoire2Carnetdadresse" primaryKey="//@schema/@tables.3/@fields.0 //@schema/@tables.3/@fields.1">
      <fields name="id_fp94N3ubdV" dataType="integer"/>
      <fields name="id_MGR7Rpm4rz" dataType="integer"/>
    </tables>
    <tables name="Fiche2Rpertoire" primaryKey="//@schema/@tables.4/@fields.0 //@schema/@tables.4/@fields.1">
      <fields name="id_nOXU6aUquV" dataType="integer"/>
      <fields name="id_fp94N3ubdV" dataType="integer"/>
    </tables>
  </schema>
</WebSite:Project>
