<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="common"
    nsURI="http://www.kerblue.org/common/1.0/" nsPrefix="common">
  <eClassifiers xsi:type="ecore:EClass" name="ModelElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="stereotypes" upperBound="-1"
        eType="#//Stereotype"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tags" upperBound="-1" eType="#//Tag"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="comments" upperBound="-1"
        eType="#//Comment" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NamedModelElement" eSuperTypes="#//ModelElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="documentation" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Comment" eSuperTypes="#//ModelElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tag">
    <eOperations name="equalsForMerge" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eAnnotations source="http://www.bluexml.com/OCL">
        <details key="body" value="self.key = other.key"/>
      </eAnnotations>
      <eParameters name="other" eType="#//Tag"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Stereotype" eSuperTypes="#//NamedModelElement">
    <eOperations name="EqualsForMerge" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eAnnotations source="http://www.bluexml.com/OCL">
        <details key="body" value="self.name = other.name"/>
      </eAnnotations>
      <eParameters name="other" eType="#//Stereotype"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Package" eSuperTypes="#//NamedModelElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="PackageNameNull"/>
    </eAnnotations>
    <eAnnotations source="http://www.bluexml.com/OCL">
      <details key="PackageNameNull" value="not self.name.oclIsUndefined() and self.name &lt;> ''"/>
    </eAnnotations>
    <eOperations name="equalsForMerge" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eAnnotations source="http://www.bluexml.com/OCL">
        <details key="body" value="self.name = other.name"/>
      </eAnnotations>
      <eParameters name="other" eType="#//Package"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="stereotypeSet" upperBound="-1"
        eType="#//Stereotype" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="packageSet" upperBound="-1"
        eType="#//Package" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
