<?xml version="1.0" encoding="UTF-8"?>
<rwm:RequirementsDefinition xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:rwm="http://rwm" xmi:id="_TnQCYKb7Edyg0-Q2ek6f8g"
    name="MyRequirements">
  <goals xmi:id="ooQGkFIbGp" name="Gestion de carnet d'adresses" documentation=""
      x="494" y="32" width="183" height="42">
    <subgoals xmi:id="bUa55Oe2Bt" name="Saisir les informations" documentation=""
        x="209" y="148" width="148" height="42" responsible="#bhxkQIbVyT">
      <privilegeGroup entryPoint="#fp94N3ubdV" documentation="">
        <privileges element="#nOXU6aUquV"/>
        <privileges element="#nOXU6aUquV" category="read"/>
        <privileges element="#nOXU6aUquV" category="update"/>
        <privileges element="#xHzgoFlUJi" category="read"/>
        <privileges element="#xHzgoFlUJi" category="update"/>
        <privileges element="#Os0kTZR4Gi" category="read"/>
        <privileges element="#Os0kTZR4Gi" category="update"/>
        <privileges element="#mVlB6SaVgl" category="read"/>
        <privileges element="#mVlB6SaVgl" category="update"/>
        <privileges element="#ZRQP0eWzzu" category="read"/>
        <privileges element="#ZRQP0eWzzu" category="update"/>
        <privileges element="#v3h6nFFZLK" category="read"/>
        <privileges element="#v3h6nFFZLK" category="update"/>
        <privileges element="#wqqpBhCXQG" category="read"/>
        <privileges element="#wqqpBhCXQG" category="update"/>
        <privileges element="#PtQei3VCul" category="read"/>
        <privileges element="#PtQei3VCul" category="update"/>
        <privileges element="#fp94N3ubdV" category="read"/>
        <privileges element="#1Cne2JNBGT" category="read"/>
      </privilegeGroup>
    </subgoals>
    <subgoals xmi:id="dcp3FSTMOz" name="Consulter les informations" documentation=""
        x="191" y="331" width="167" height="42" responsible="#A4RyC0lg0U">
      <privilegeGroup entryPoint="#fp94N3ubdV" documentation="">
        <privileges element="#1Cne2JNBGT" category="read"/>
        <privileges element="#nOXU6aUquV" category="read"/>
        <privileges element="#mVlB6SaVgl" category="read"/>
        <privileges element="#v3h6nFFZLK" category="read"/>
        <privileges element="#xHzgoFlUJi" category="read"/>
        <privileges element="#Os0kTZR4Gi" category="read"/>
        <privileges element="#PtQei3VCul" category="read"/>
        <privileges element="#wqqpBhCXQG" category="read"/>
        <privileges element="#ZRQP0eWzzu" category="read"/>
      </privilegeGroup>
    </subgoals>
    <subgoals xmi:id="DTdwz9LcOn" name="Analyser les informations" documentation=""
        x="876" y="563" width="163" height="42" responsible="#2U7KFEpZh6">
      <privilegeGroup entryPoint="#nOXU6aUquV" documentation="">
        <privileges element="#nOXU6aUquV" category="read"/>
        <privileges element="#Os0kTZR4Gi" category="read"/>
        <privileges element="#PtQei3VCul" category="read"/>
      </privilegeGroup>
    </subgoals>
    <subgoals xmi:id="nwEB8IhcRP" name="Administrer les informations" documentation=""
        x="865" y="161" width="176" height="42" responsible="#o14LzByM3t">
      <privilegeGroup entryPoint="#MGR7Rpm4rz" documentation="">
        <privileges element="#MGR7Rpm4rz"/>
        <privileges element="#MGR7Rpm4rz" category="read"/>
        <privileges element="#fp94N3ubdV"/>
        <privileges element="#fp94N3ubdV" category="read"/>
        <privileges element="#fp94N3ubdV" category="update"/>
        <privileges element="#1Cne2JNBGT" category="read"/>
        <privileges element="#1Cne2JNBGT" category="update"/>
        <privileges element="#nOXU6aUquV" category="read"/>
        <privileges element="#mVlB6SaVgl" category="read"/>
        <privileges element="#v3h6nFFZLK" category="read"/>
        <privileges element="#xHzgoFlUJi" category="read"/>
        <privileges element="#Os0kTZR4Gi" category="read"/>
        <privileges element="#PtQei3VCul" category="read"/>
        <privileges element="#wqqpBhCXQG" category="read"/>
        <privileges element="#ZRQP0eWzzu" category="read"/>
      </privilegeGroup>
    </subgoals>
    <subgoals xmi:id="PyNiT9GOWR" name="Mettre à jour les informations" documentation=""
        x="880" y="276" width="119" height="54" responsible="#ns5HgIOorM">
      <privilegeGroup entryPoint="#fp94N3ubdV" documentation="">
        <privileges element="#nOXU6aUquV" category="read"/>
        <privileges element="#nOXU6aUquV" category="update"/>
        <privileges element="#xHzgoFlUJi" category="read"/>
        <privileges element="#xHzgoFlUJi" category="update"/>
        <privileges element="#Os0kTZR4Gi" category="read"/>
        <privileges element="#Os0kTZR4Gi" category="update"/>
        <privileges element="#mVlB6SaVgl" category="read"/>
        <privileges element="#mVlB6SaVgl" category="update"/>
        <privileges element="#ZRQP0eWzzu" category="read"/>
        <privileges element="#ZRQP0eWzzu" category="update"/>
        <privileges element="#v3h6nFFZLK" category="read"/>
        <privileges element="#v3h6nFFZLK" category="update"/>
        <privileges element="#wqqpBhCXQG" category="read"/>
        <privileges element="#wqqpBhCXQG" category="update"/>
        <privileges element="#PtQei3VCul" category="read"/>
        <privileges element="#PtQei3VCul" category="update"/>
        <privileges element="#fp94N3ubdV" category="read"/>
        <privileges element="#fp94N3ubdV" category="update"/>
        <privileges element="#1Cne2JNBGT" category="read"/>
        <privileges element="#1Cne2JNBGT" category="update"/>
      </privilegeGroup>
    </subgoals>
  </goals>
  <sub xmi:id="Xy6verT0Uv" name="Pôle assistante" documentation="" x="66" y="36" width="315"
      height="188">
    <members xmi:id="bhxkQIbVyT" name="Assistante" documentation="" x="86" y="68"
        width="48" height="70" isHuman="true" isResponsible="#bUa55Oe2Bt"/>
  </sub>
  <sub xmi:id="VMv2dEgclX" name="Centre d'appel" documentation="" x="844" y="223"
      width="301" height="205">
    <members xmi:id="ns5HgIOorM" name="Télé conseiller" documentation="" x="1069"
        y="313" width="48" height="70" isHuman="true" isResponsible="#PyNiT9GOWR"/>
  </sub>
  <sub xmi:id="xdeMwXL44d" name="Centre d'analyse" documentation="" x="846" y="428"
      width="302" height="210">
    <members xmi:id="2U7KFEpZh6" name="Analyste" documentation="" x="1084" y="458"
        width="48" height="70" isHuman="true" isResponsible="#DTdwz9LcOn"/>
  </sub>
  <sub xmi:id="UrsEfeBrL9" name="Administration" documentation="" x="842" y="20" width="303"
      height="205">
    <members xmi:id="o14LzByM3t" name="Administrateur" documentation="" x="1061" y="55"
        width="48" height="70" isHuman="true" isResponsible="#nwEB8IhcRP"/>
  </sub>
  <sub xmi:id="c6mAit6uQV" name="Pôle commercial" documentation="" x="66" y="228"
      width="315" height="180">
    <members xmi:id="A4RyC0lg0U" name="Commercial" documentation="" x="81" y="259"
        width="48" height="70" isHuman="true" isResponsible="#dcp3FSTMOz"/>
  </sub>
  <entities xmi:id="MGR7Rpm4rz" name="Carnet d'adresse" documentation="" x="516" y="201"
      width="200" height="50"/>
  <entities xmi:id="fp94N3ubdV" name="Répertoire" documentation="" x="442" y="398"
      width="200" height="55">
    <attributes xmi:id="1Cne2JNBGT" name="nom" documentation=""/>
  </entities>
  <entities xmi:id="nOXU6aUquV" name="Fiche" documentation="" x="521" y="547" width="200"
      height="193">
    <attributes xmi:id="mVlB6SaVgl" name="nom" documentation=""/>
    <attributes xmi:id="v3h6nFFZLK" name="prénom" documentation=""/>
    <attributes xmi:id="xHzgoFlUJi" name="adresse" documentation=""/>
    <attributes xmi:id="Os0kTZR4Gi" name="code postal" documentation=""/>
    <attributes xmi:id="PtQei3VCul" name="ville" documentation=""/>
    <attributes xmi:id="wqqpBhCXQG" name="téléphone" documentation="" type="NumericalValue"/>
    <attributes xmi:id="ZRQP0eWzzu" name="portable" documentation="" type="NumericalValue"/>
  </entities>
  <relations xmi:id="nV1EcMy9u8" name="contient" documentation="">
    <ends object="#fp94N3ubdV" maxCardinality="-1"/>
    <ends object="#MGR7Rpm4rz" minCardinality="1" maxCardinality="1"/>
  </relations>
  <relations xmi:id="XOcs1StRQG" name="fiches" documentation="">
    <ends object="#nOXU6aUquV" maxCardinality="-1"/>
    <ends object="#fp94N3ubdV" maxCardinality="1"/>
  </relations>
</rwm:RequirementsDefinition>
