<?xml version="1.0" encoding="UTF-8"?>
<rwm:RequirementsDefinition xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:rwm="http://rwm" xmi:id="_TnQCYKb7Edyg0-Q2ek6f8g"
    name="MyRequirements">
  <members xmi:id="bhxkQIbVyT" name="Assistante" documentation="Le groupe nommé &amp;lt;i>Assistante &amp;lt;/i>regroupe l'ensemble des personnels attachés à  un service administratif. Ce groupe a pour charge de stocker dans l'application l'ensemble des contacts obtenus pendant leurs différentes missions.&amp;lt;br>"
      x="134" y="47" width="48" height="70" isHuman="true" isResponsible="#bUa55Oe2Bt"/>
  <members xmi:id="ns5HgIOorM" name="Télé conseiller" documentation="Le groupe Télé conseiller est chargé de communiquer avec les différents contacts stockés dans les fiches mais son objectif est de maintenir une base d'informations à  jour qui seront ensuite utilisée par les commerciaux.&amp;lt;br&amp;gt;"
      x="1026" y="123" width="48" height="70" isHuman="true" isResponsible="#PyNiT9GOWR"/>
  <members xmi:id="2U7KFEpZh6" name="Analyste" documentation="Le groupe &amp;lt;i&amp;gt;Analyste&amp;lt;/i&amp;gt; de l'entreprise a pour tâche d'analyser les différentes communications avec l'extérieur et d'informer les dirigeants sur les différents profils existants dans l'ensemble des fiches. L'analyse se résume à  une étude de la répartition géographique des contacts.&amp;lt;br&amp;gt;"
      x="1026" y="212" width="48" height="70" isHuman="true" isResponsible="#DTdwz9LcOn"/>
  <members xmi:id="o14LzByM3t" name="Administrateur" documentation="Il est toujours nécessaire d'avoir un administrateur dans une application. C'est le seul profil qui a le droit de créer des carnets d'adresse et des répertoires.&amp;lt;br&amp;gt;"
      x="1023" y="34" width="48" height="70" isHuman="true" isResponsible="#nwEB8IhcRP"/>
  <members xmi:id="A4RyC0lg0U" name="Commercial" documentation="Le groupe &amp;lt;i>Commercial &amp;lt;/i>a pour objectif d'utiliser l'ensemble des fiches saisies afin de vendre différents produits ou services.&amp;lt;br>"
      x="86" y="256" width="48" height="70" isHuman="true" isResponsible="#dcp3FSTMOz"/>
  <goals xmi:id="ooQGkFIbGp" name="Gestion de carnet d'adresses" documentation="L'objectif de l'application est de g̩rer un carnet d'adresses avec diff̩rentes fiches. Cet exemple a pour objectif d'illustrer la d̩marche simplifi̩e d'expression des besoins.&amp;lt;br>"
      x="508" y="23" width="183" height="42" priority="Normal">
    <subgoals xmi:id="PyNiT9GOWR" name="Mettre à jour les informations" documentation="Cet objectif doit maintenir les données à  jour afin qu'elles soient de meilleure qualité. Cet objectif facilite donc le travail du groupe &amp;lt;i>Commercial&amp;lt;/i>.&amp;lt;br>"
        x="784" y="235" width="182" height="42" priority="Normal" responsible="#ns5HgIOorM">
      <privilegeGroup entryPoint="#fp94N3ubdV" documentation="">
        <privileges element="#nOXU6aUquV" category="read"/>
        <privileges element="#nOXU6aUquV" category="update"/>
        <privileges element="#QysZxiFw5P" category="read"/>
        <privileges element="#QysZxiFw5P" category="update"/>
        <privileges element="#k77yWEUTLJ" category="read"/>
        <privileges element="#k77yWEUTLJ" category="update"/>
        <privileges element="#F1C4F44QLb" category="read"/>
        <privileges element="#F1C4F44QLb" category="update"/>
        <privileges element="#ZRQP0eWzzu" category="read"/>
        <privileges element="#ZRQP0eWzzu" category="update"/>
        <privileges element="#a1rX5c5vei" category="read"/>
        <privileges element="#a1rX5c5vei" category="update"/>
        <privileges element="#WohhlvohVA" category="read"/>
        <privileges element="#WohhlvohVA" category="update"/>
        <privileges element="#AFqm04RFiJ" category="read"/>
        <privileges element="#AFqm04RFiJ" category="update"/>
        <privileges element="#fp94N3ubdV" category="read"/>
        <privileges element="#fp94N3ubdV" category="update"/>
        <privileges element="#1Cne2JNBGT" category="read"/>
        <privileges element="#1Cne2JNBGT" category="update"/>
      </privilegeGroup>
    </subgoals>
    <subgoals xmi:id="nwEB8IhcRP" name="Administrer les informations" documentation="Cet objectif permet d'administrer les informations et donc de créer des carnets d'adresses et des répertoires.&amp;lt;br&amp;gt;"
        x="751" y="113" width="176" height="42" priority="Normal" responsible="#o14LzByM3t">
      <privilegeGroup entryPoint="#MGR7Rpm4rz" documentation="">
        <privileges element="#MGR7Rpm4rz"/>
        <privileges element="#MGR7Rpm4rz" category="read"/>
        <privileges element="#fp94N3ubdV"/>
        <privileges element="#fp94N3ubdV" category="read"/>
        <privileges element="#fp94N3ubdV" category="update"/>
        <privileges element="#1Cne2JNBGT" category="read"/>
        <privileges element="#1Cne2JNBGT" category="update"/>
        <privileges element="#nOXU6aUquV" category="read"/>
        <privileges element="#F1C4F44QLb" category="read"/>
        <privileges element="#a1rX5c5vei" category="read"/>
        <privileges element="#QysZxiFw5P" category="read"/>
        <privileges element="#k77yWEUTLJ" category="read"/>
        <privileges element="#AFqm04RFiJ" category="read"/>
        <privileges element="#WohhlvohVA" category="read"/>
        <privileges element="#ZRQP0eWzzu" category="read"/>
      </privilegeGroup>
    </subgoals>
    <subgoals xmi:id="DTdwz9LcOn" name="Analyser les informations" documentation="Il est toujours nécessaire d'analyser les informations stock̩es par une application. Cette analyse permet d'avoir une meilleure vue sur les différents contacts et donc d'adapter les différentes prestations de l'entreprise afin d'améliorer ses performances.&amp;lt;br>"
        x="746" y="373" width="163" height="42" priority="Normal" responsible="#2U7KFEpZh6">
      <privilegeGroup entryPoint="#nOXU6aUquV" documentation="">
        <privileges element="#nOXU6aUquV" category="read"/>
        <privileges element="#k77yWEUTLJ" category="read"/>
        <privileges element="#AFqm04RFiJ" category="read"/>
      </privilegeGroup>
    </subgoals>
    <subgoals xmi:id="dcp3FSTMOz" name="Consulter les informations" documentation="Cet objectif permet de consulter les informations de chaque fiche ajoutée dans l'application.&amp;lt;br>"
        x="185" y="330" width="167" height="42" priority="Normal" responsible="#A4RyC0lg0U">
      <privilegeGroup entryPoint="#fp94N3ubdV" documentation="">
        <privileges element="#1Cne2JNBGT" category="read"/>
        <privileges element="#nOXU6aUquV" category="read"/>
        <privileges element="#F1C4F44QLb" category="read"/>
        <privileges element="#a1rX5c5vei" category="read"/>
        <privileges element="#QysZxiFw5P" category="read"/>
        <privileges element="#k77yWEUTLJ" category="read"/>
        <privileges element="#AFqm04RFiJ" category="read"/>
        <privileges element="#WohhlvohVA" category="read"/>
        <privileges element="#ZRQP0eWzzu" category="read"/>
      </privilegeGroup>
    </subgoals>
    <subgoals xmi:id="bUa55Oe2Bt" name="Saisir les informations" documentation="Cet objectif se résume à  la saisie d'informations.&amp;lt;br>"
        x="218" y="146" width="148" height="42" priority="Normal" responsible="#bhxkQIbVyT">
      <privilegeGroup entryPoint="#fp94N3ubdV" documentation="">
        <privileges element="#nOXU6aUquV"/>
        <privileges element="#nOXU6aUquV" category="read"/>
        <privileges element="#nOXU6aUquV" category="update"/>
        <privileges element="#QysZxiFw5P" category="read"/>
        <privileges element="#QysZxiFw5P" category="update"/>
        <privileges element="#k77yWEUTLJ" category="read"/>
        <privileges element="#k77yWEUTLJ" category="update"/>
        <privileges element="#F1C4F44QLb" category="read"/>
        <privileges element="#F1C4F44QLb" category="update"/>
        <privileges element="#ZRQP0eWzzu" category="read"/>
        <privileges element="#ZRQP0eWzzu" category="update"/>
        <privileges element="#a1rX5c5vei" category="read"/>
        <privileges element="#a1rX5c5vei" category="update"/>
        <privileges element="#WohhlvohVA" category="read"/>
        <privileges element="#WohhlvohVA" category="update"/>
        <privileges element="#AFqm04RFiJ" category="read"/>
        <privileges element="#AFqm04RFiJ" category="update"/>
        <privileges element="#fp94N3ubdV" category="read"/>
        <privileges element="#1Cne2JNBGT" category="read"/>
      </privilegeGroup>
    </subgoals>
  </goals>
  <entities xmi:id="MGR7Rpm4rz" name="Carnet d'adresse" documentation="Le carnet d'adresse est le noyau de la structure d'information. Il est composé de différents répertoires.&amp;lt;br&amp;gt;"
      x="463" y="183" width="200" height="50"/>
  <entities xmi:id="fp94N3ubdV" name="Répertoire" documentation="Un répertoire est un ensemble de fiches. L'ensemble des r̩pertoires sont partagés dans l'entreprise. Un répertoire est caractérisé par son nom qui doit être unique.&amp;lt;br&amp;gt;"
      x="475" y="293" width="200" height="55">
    <attributes xmi:id="1Cne2JNBGT" name="nom" documentation="Le nom d'un répertoire est son identifiant unique.&amp;lt;br>"/>
  </entities>
  <entities xmi:id="nOXU6aUquV" name="Fiche" documentation="Une fiche est un ensemble d'informations concernant une personne. Elle regroupe son nom, son pr̩nom, son adresse, son code postal et sa ville mais ̩galement son t̩l̩phone et son portable.&amp;lt;br>"
      x="318" y="397" width="200" height="193">
    <attributes xmi:id="F1C4F44QLb" name="nom" documentation="Nom de la personne&amp;lt;br>"/>
    <attributes xmi:id="a1rX5c5vei" name="prénom" documentation="Prénom de la personne&amp;lt;br>"/>
    <attributes xmi:id="QysZxiFw5P" name="adresse" documentation="Adresse complète de la personne&amp;lt;br>"/>
    <attributes xmi:id="k77yWEUTLJ" name="code postal" documentation="Code postal de l'adresse&amp;lt;br>"/>
    <attributes xmi:id="AFqm04RFiJ" name="ville" documentation="Ville de l'adresse&amp;lt;br>"/>
    <attributes xmi:id="WohhlvohVA" name="téléphone" documentation="" type="NumericalValue"/>
    <attributes xmi:id="ZRQP0eWzzu" name="portable" documentation="" type="NumericalValue"/>
  </entities>
  <relations xmi:id="6FrpnUM1bh" name="contient" documentation="">
    <ends object="#fp94N3ubdV" maxCardinality="-1"/>
    <ends object="#MGR7Rpm4rz" minCardinality="1" maxCardinality="1"/>
  </relations>
  <relations xmi:id="Eebo47Thfq" name="fiches" documentation="">
    <ends object="#nOXU6aUquV" maxCardinality="-1"/>
    <ends object="#fp94N3ubdV" maxCardinality="1"/>
  </relations>
</rwm:RequirementsDefinition>
