<?xml version="1.0" encoding="UTF-8"?>
<rwm:RequirementsDefinition xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:rwm="http://rwm" xmi:id="_TnQCYKb7Edyg0-Q2ek6f8g"
    name="MyRequirements">
  <members xmi:id="ILQvQsbVaT" name="Manager" documentation="" x="1941" y="340" width="48"
      height="70" isHuman="true" isResponsible="#0SUGwB33ar #sBlEvfNt4f #Dtm28JKtn3 #Bg7I7xuUKF #mMzNVsTN7z #Wkpc73g0tH #OPilINtBGi #lyFB0uzW6U #tDIa1n9GaA #D1M2omzOCH #3P9ryemQfm #vFr8JTEawa"/>
  <members xmi:id="C0TMn0m4V6" name="Assistante" documentation="" x="1942" y="451"
      width="48" height="70" isHuman="true" isResponsible="#0SUGwB33ar #sBlEvfNt4f #Dtm28JKtn3 #Bg7I7xuUKF #mMzNVsTN7z #Wkpc73g0tH #tDIa1n9GaA"/>
  <goals xmi:id="IkKdaZgu58" name="Portail Collaboratif SEM" documentation="Documentation du portail"
      x="1481" y="24" width="150" height="42" priority="Normal">
    <subgoals xmi:id="CNpNqPHDJ2" name="Gestion Documentaire" documentation="" x="2066"
        y="222" width="146" height="42" priority="Normal">
      <subgoals xmi:id="3P9ryemQfm" name="Creer un repertoire de stockage" documentation=""
          x="2246" y="302" width="194" height="42" priority="Normal" responsible="#ILQvQsbVaT">
        <privilegeGroup entryPoint="#fkHhRpNdDn" documentation="">
          <privileges element="#fkHhRpNdDn"/>
          <privileges element="#fkHhRpNdDn" category="update"/>
        </privilegeGroup>
      </subgoals>
      <subgoals xmi:id="D1M2omzOCH" name="Gerer les versions des documents" documentation=""
          x="2248" y="371" width="207" height="42" priority="Normal" responsible="#ILQvQsbVaT">
        <privilegeGroup entryPoint="#OdwF49GfSM" documentation=""/>
      </subgoals>
      <subgoals xmi:id="tDIa1n9GaA" name="Creer/Modifier/Supprimer un document" documentation=""
          x="2248" y="441" width="225" height="42" priority="Normal" responsible="#C0TMn0m4V6 #ILQvQsbVaT">
        <privilegeGroup entryPoint="#OdwF49GfSM" documentation="">
          <privileges element="#OdwF49GfSM"/>
          <privileges element="#OdwF49GfSM" category="read"/>
          <privileges element="#OdwF49GfSM" category="update"/>
          <privileges element="#VkSLHzhddP" category="read"/>
          <privileges element="#VkSLHzhddP" category="update"/>
          <privileges element="#K5po4rPTkA" category="read"/>
          <privileges element="#K5po4rPTkA" category="update"/>
          <privileges element="#fnirTktsVh" category="read"/>
        </privilegeGroup>
      </subgoals>
      <subgoals xmi:id="lyFB0uzW6U" name="Creer des Regles de gestion" documentation=""
          x="2249" y="507" width="177" height="42" priority="Normal" responsible="#ILQvQsbVaT">
        <privilegeGroup entryPoint="#UI55xfJhzF" documentation="">
          <privileges element="#UI55xfJhzF"/>
          <privileges element="#UI55xfJhzF" category="read"/>
          <privileges element="#UI55xfJhzF" category="update"/>
        </privilegeGroup>
      </subgoals>
      <subgoals xmi:id="OPilINtBGi" name="Relire et valider des documents" documentation=""
          x="2246" y="575" width="189" height="42" priority="Normal" responsible="#ILQvQsbVaT">
        <privilegeGroup entryPoint="#OdwF49GfSM" documentation="">
          <privileges element="#OdwF49GfSM" category="read"/>
          <privileges element="#VkSLHzhddP" category="read"/>
          <privileges element="#K5po4rPTkA" category="read"/>
          <privileges element="#auddNpHQTy" category="read"/>
          <privileges element="#fnirTktsVh" category="read"/>
        </privilegeGroup>
      </subgoals>
      <subgoals xmi:id="Wkpc73g0tH" name="Rechercher des documents" documentation=""
          x="2255" y="644" width="174" height="42" priority="Normal" responsible="#C0TMn0m4V6 #ILQvQsbVaT">
        <privilegeGroup entryPoint="#OdwF49GfSM" documentation="">
          <privileges element="#OdwF49GfSM" category="read"/>
          <privileges element="#VkSLHzhddP" category="read"/>
          <privileges element="#K5po4rPTkA" category="read"/>
          <privileges element="#auddNpHQTy" category="read"/>
          <privileges element="#fnirTktsVh" category="read"/>
        </privilegeGroup>
      </subgoals>
    </subgoals>
    <subgoals xmi:id="8k54LXsCrk" name="Gestion des Ateliers" documentation="" x="1403"
        y="246" width="138" height="42" priority="Normal">
      <subgoals xmi:id="mMzNVsTN7z" name="Creer un Comite de Pilotage" documentation=""
          x="1609" y="302" width="172" height="42" priority="Normal" responsible="#C0TMn0m4V6 #ILQvQsbVaT">
        <privilegeGroup entryPoint="#7guHOgNEIK" documentation="">
          <privileges element="#eKVaZOtQ8o"/>
          <privileges element="#eKVaZOtQ8o" category="read"/>
          <privileges element="#eKVaZOtQ8o" category="update"/>
          <privileges element="#aGEBOKMw47" category="read"/>
          <privileges element="#aGEBOKMw47" category="update"/>
          <privileges element="#4o9UxgVcRa" category="read"/>
          <privileges element="#gVdhMORFVU" category="read"/>
          <privileges element="#MW6mDUdGmW" category="read"/>
        </privilegeGroup>
      </subgoals>
      <subgoals xmi:id="Bg7I7xuUKF" name="Creer un Comite Technique" documentation=""
          x="1611" y="384" width="170" height="42" priority="Normal" responsible="#C0TMn0m4V6 #ILQvQsbVaT">
        <privilegeGroup entryPoint="#7guHOgNEIK" documentation="">
          <privileges element="#7guHOgNEIK" category="read"/>
          <privileges element="#7guHOgNEIK" category="update"/>
          <privileges element="#eKVaZOtQ8o"/>
          <privileges element="#eKVaZOtQ8o" category="read"/>
          <privileges element="#eKVaZOtQ8o" category="update"/>
          <privileges element="#aGEBOKMw47" category="read"/>
          <privileges element="#aGEBOKMw47" category="update"/>
          <privileges element="#4o9UxgVcRa" category="read"/>
          <privileges element="#gVdhMORFVU" category="read"/>
          <privileges element="#MW6mDUdGmW" category="read"/>
        </privilegeGroup>
      </subgoals>
      <subgoals xmi:id="Dtm28JKtn3" name="Publiposter une invitation" documentation=""
          x="1611" y="451" width="159" height="42" priority="Normal" responsible="#C0TMn0m4V6 #ILQvQsbVaT">
        <privilegeGroup entryPoint="#7guHOgNEIK" documentation="">
          <privileges element="#7guHOgNEIK" category="read"/>
          <privileges element="#7guHOgNEIK" category="update"/>
          <privileges element="#eKVaZOtQ8o" category="read"/>
          <privileges element="#0JfzyXhDDM" category="read"/>
          <privileges element="#0JfzyXhDDM" category="update"/>
          <privileges element="#4o9UxgVcRa" category="read"/>
        </privilegeGroup>
      </subgoals>
      <subgoals xmi:id="sBlEvfNt4f" name="Gerer les inscriptions" documentation=""
          x="1614" y="519" width="143" height="42" priority="Normal" responsible="#C0TMn0m4V6 #ILQvQsbVaT">
        <privilegeGroup entryPoint="#7guHOgNEIK" documentation="">
          <privileges element="#0JfzyXhDDM" category="read"/>
          <privileges element="#0JfzyXhDDM" category="update"/>
          <privileges element="#eKVaZOtQ8o" category="read"/>
        </privilegeGroup>
      </subgoals>
      <subgoals xmi:id="0SUGwB33ar" name="Gerer les presences/absences" documentation=""
          x="1615" y="596" width="191" height="42" priority="Normal" responsible="#C0TMn0m4V6 #ILQvQsbVaT"/>
      <privilegeGroup entryPoint="#7guHOgNEIK" documentation="">
        <privileges element="#7guHOgNEIK"/>
        <privileges element="#7guHOgNEIK" category="read"/>
        <privileges element="#7guHOgNEIK" category="update"/>
        <privileges element="#yZEDHrfF2V" category="read"/>
        <privileges element="#yZEDHrfF2V" category="update"/>
        <privileges element="#zMVvwwH0k8" category="read"/>
        <privileges element="#zMVvwwH0k8" category="update"/>
        <privileges element="#yaykzPmhtg" category="read"/>
        <privileges element="#yaykzPmhtg" category="update"/>
      </privilegeGroup>
    </subgoals>
    <subgoals xmi:id="cJZ4m2RrZz" name="Gestion de la Clientele" documentation="Partie CRM&amp;lt;br>"
        x="377" y="184" width="146" height="42" priority="Normal">
      <subgoals xmi:id="vFr8JTEawa" name="Gestion des Contacts" documentation="" x="10"
          y="338" width="144" height="42" priority="Normal" responsible="#ILQvQsbVaT">
        <subgoals xmi:id="eRb09xgrTJ" name="Creer/Modifier/Supprimer un contact" documentation=""
            x="185" y="382" width="214" height="42" priority="Normal">
          <privilegeGroup entryPoint="#4o9UxgVcRa" documentation="">
            <privileges element="#4o9UxgVcRa"/>
            <privileges element="#4o9UxgVcRa" category="read"/>
            <privileges element="#4o9UxgVcRa" category="update"/>
            <privileges element="#hQ64CUVW7G" category="read"/>
            <privileges element="#hQ64CUVW7G" category="update"/>
            <privileges element="#dn1W84vZ8u" category="read"/>
            <privileges element="#dn1W84vZ8u" category="update"/>
            <privileges element="#aADck4qWQT" category="read"/>
            <privileges element="#aADck4qWQT" category="update"/>
            <privileges element="#gVdhMORFVU" category="read"/>
            <privileges element="#gVdhMORFVU" category="update"/>
            <privileges element="#MW6mDUdGmW" category="read"/>
            <privileges element="#MW6mDUdGmW" category="update"/>
            <privileges element="#tBARma7XvR" category="read"/>
            <privileges element="#tBARma7XvR" category="update"/>
            <privileges element="#fnirTktsVh" category="read"/>
            <privileges element="#TEexzsSvyI" category="read"/>
          </privilegeGroup>
        </subgoals>
        <subgoals xmi:id="mDiVnc8Fz0" name="Creer un lien entre contact et entite (Role)"
            documentation="" x="185" y="665" width="241" height="42" priority="Normal">
          <privilegeGroup entryPoint="#TEexzsSvyI" documentation="">
            <privileges element="#TEexzsSvyI"/>
            <privileges element="#TEexzsSvyI" category="read"/>
            <privileges element="#TEexzsSvyI" category="update"/>
            <privileges element="#VygyRKkMHu" category="read"/>
            <privileges element="#VygyRKkMHu" category="update"/>
            <privileges element="#cIA9J7xD34" category="read"/>
            <privileges element="#cIA9J7xD34" category="update"/>
            <privileges element="#woAT1fgTih" category="read"/>
            <privileges element="#4o9UxgVcRa" category="read"/>
          </privilegeGroup>
        </subgoals>
        <subgoals xmi:id="kbiqer8NBe" name="Creer une action relative a  un contact"
            documentation="un rendez-vous, une reunion, un atelier&amp;lt;br>" x="196"
            y="573" width="221" height="42" priority="Normal">
          <privilegeGroup entryPoint="#ukf6ayXH9x" documentation="">
            <privileges element="#ukf6ayXH9x"/>
            <privileges element="#ukf6ayXH9x" category="read"/>
            <privileges element="#ukf6ayXH9x" category="update"/>
            <privileges element="#nPEIE4r4rn" category="read"/>
            <privileges element="#nPEIE4r4rn" category="update"/>
            <privileges element="#duLGX9Krif" category="read"/>
            <privileges element="#duLGX9Krif" category="update"/>
            <privileges element="#xTvGuzXbtW" category="read"/>
            <privileges element="#xTvGuzXbtW" category="update"/>
            <privileges element="#4o9UxgVcRa" category="read"/>
          </privilegeGroup>
        </subgoals>
        <subgoals xmi:id="0kXWCSsSAG" name="Regrouper des contacts" documentation=""
            x="184" y="465" width="157" height="42" priority="Normal">
          <privilegeGroup entryPoint="#4o9UxgVcRa" documentation="">
            <privileges element="#4o9UxgVcRa" category="read"/>
            <privileges element="#gVdhMORFVU" category="read"/>
            <privileges element="#MW6mDUdGmW" category="read"/>
          </privilegeGroup>
        </subgoals>
        <subgoals xmi:id="Q0P1kXlAEh" name="Assigner une filiere (choix restreint)"
            documentation="" x="188" y="786" width="214" height="42" priority="Normal">
          <privilegeGroup entryPoint="#fnirTktsVh" documentation="">
            <privileges element="#fnirTktsVh" category="read"/>
            <privileges element="#NkRd3y0ha2" category="read"/>
          </privilegeGroup>
        </subgoals>
      </subgoals>
      <subgoals xmi:id="giEZEo3JsC" name="Gestion des Entites" documentation="" x="464"
          y="339" width="133" height="42" priority="Normal">
        <subgoals xmi:id="lntWfHl7wF" name="Creer/Modifier/Supprimer une Entite" documentation=""
            x="586" y="399" width="210" height="42" priority="Normal">
          <privilegeGroup entryPoint="#woAT1fgTih" documentation="">
            <privileges element="#woAT1fgTih"/>
            <privileges element="#woAT1fgTih" category="read"/>
            <privileges element="#woAT1fgTih" category="update"/>
            <privileges element="#aemWVyCAva" category="read"/>
            <privileges element="#aemWVyCAva" category="update"/>
            <privileges element="#d4LeuuLwXC" category="read"/>
            <privileges element="#d4LeuuLwXC" category="update"/>
            <privileges element="#f5K7qKqwkD" category="read"/>
            <privileges element="#f5K7qKqwkD" category="update"/>
            <privileges element="#rWCxAAtnhs" category="read"/>
            <privileges element="#rWCxAAtnhs" category="update"/>
            <privileges element="#QC2y6FXaS5" category="read"/>
            <privileges element="#QC2y6FXaS5" category="update"/>
            <privileges element="#zcO6T0kWNI" category="read"/>
            <privileges element="#zcO6T0kWNI" category="update"/>
            <privileges element="#xAeIoMTTcr" category="read"/>
            <privileges element="#xAeIoMTTcr" category="update"/>
            <privileges element="#yWyKlQvGqU" category="read"/>
            <privileges element="#yWyKlQvGqU" category="update"/>
            <privileges element="#Kb2EgkIUoM" category="read"/>
            <privileges element="#Kb2EgkIUoM" category="update"/>
            <privileges element="#uUL3EQ04Op" category="read"/>
            <privileges element="#uUL3EQ04Op" category="update"/>
            <privileges element="#LiPt9bppFE" category="read"/>
            <privileges element="#LiPt9bppFE" category="update"/>
            <privileges element="#JK6ZfewHSp" category="read"/>
            <privileges element="#JK6ZfewHSp" category="update"/>
            <privileges element="#fnirTktsVh" category="read"/>
            <privileges element="#TEexzsSvyI" category="read"/>
          </privilegeGroup>
        </subgoals>
        <subgoals xmi:id="zchADAcoAo" name="Regrouper des entites" documentation=""
            x="594" y="477" width="147" height="42" priority="Normal">
          <privilegeGroup entryPoint="#woAT1fgTih" documentation="">
            <privileges element="#woAT1fgTih" category="read"/>
            <privileges element="#yWyKlQvGqU" category="read"/>
          </privilegeGroup>
        </subgoals>
        <subgoals xmi:id="K5XXKKgazS" name="Creer et assigner une filiere" documentation=""
            x="590" y="665" width="174" height="42" priority="Normal">
          <privilegeGroup entryPoint="#woAT1fgTih" documentation="">
            <privileges element="#fnirTktsVh"/>
            <privileges element="#fnirTktsVh" category="read"/>
            <privileges element="#fnirTktsVh" category="update"/>
            <privileges element="#NkRd3y0ha2" category="read"/>
            <privileges element="#NkRd3y0ha2" category="update"/>
          </privilegeGroup>
        </subgoals>
        <subgoals xmi:id="Tq7HtAeVME" name="Assigner une societe mere" documentation=""
            x="593" y="566" width="170" height="42" priority="Normal">
          <privilegeGroup entryPoint="#woAT1fgTih" documentation="">
            <privileges element="#LiPt9bppFE" category="update"/>
          </privilegeGroup>
        </subgoals>
      </subgoals>
      <subgoals xmi:id="JM2CJsE7XO" name="Rechercher" documentation="" x="877" y="354"
          width="97" height="42" priority="Normal">
        <subgoals xmi:id="5xo4GGJEUz" name="Rechercher sur les attributs d une classe"
            documentation="" x="1035" y="408" width="240" height="42" priority="Normal">
          <privilegeGroup entryPoint="#woAT1fgTih" documentation="">
            <privileges element="#woAT1fgTih" category="read"/>
            <privileges element="#aemWVyCAva" category="read"/>
            <privileges element="#d4LeuuLwXC" category="read"/>
            <privileges element="#f5K7qKqwkD" category="read"/>
            <privileges element="#rWCxAAtnhs" category="read"/>
            <privileges element="#QC2y6FXaS5" category="read"/>
            <privileges element="#zcO6T0kWNI" category="read"/>
            <privileges element="#xAeIoMTTcr" category="read"/>
            <privileges element="#yWyKlQvGqU" category="read"/>
            <privileges element="#Kb2EgkIUoM" category="read"/>
            <privileges element="#uUL3EQ04Op" category="read"/>
            <privileges element="#LiPt9bppFE" category="read"/>
            <privileges element="#JK6ZfewHSp" category="read"/>
            <privileges element="#fnirTktsVh" category="read"/>
            <privileges element="#TEexzsSvyI" category="read"/>
          </privilegeGroup>
        </subgoals>
        <subgoals xmi:id="avQDz334JK" name="Rechercher sur les attributs d une classe liee a  une autre classe (Filiere, Action)"
            documentation="" x="986" y="510" width="428" height="42" priority="Normal">
          <privilegeGroup entryPoint="#4o9UxgVcRa" documentation="">
            <privileges element="#4o9UxgVcRa" category="read"/>
            <privileges element="#ukf6ayXH9x" category="read"/>
            <privileges element="#duLGX9Krif" category="read"/>
            <privileges element="#xTvGuzXbtW" category="read"/>
            <privileges element="#nPEIE4r4rn" category="read"/>
            <privileges element="#fnirTktsVh" category="read"/>
            <privileges element="#NkRd3y0ha2" category="read"/>
            <privileges element="#TEexzsSvyI" category="read"/>
            <privileges element="#VygyRKkMHu" category="read"/>
            <privileges element="#cIA9J7xD34" category="read"/>
            <privileges element="#woAT1fgTih" category="read"/>
          </privilegeGroup>
        </subgoals>
      </subgoals>
    </subgoals>
  </goals>
  <entities xmi:id="4o9UxgVcRa" name="Contact" documentation="" x="507" y="902" width="200"
      height="216">
    <attributes xmi:id="gVdhMORFVU" name="Nom" documentation=""/>
    <attributes xmi:id="MW6mDUdGmW" name="Prenom" documentation=""/>
    <attributes xmi:id="dn1W84vZ8u" name="Civilite" documentation=""/>
    <attributes xmi:id="hQ64CUVW7G" name="Adresse" documentation=""/>
    <attributes xmi:id="tBARma7XvR" name="Telephone" documentation=""/>
    <attributes xmi:id="aADck4qWQT" name="Mail" documentation=""/>
  </entities>
  <entities xmi:id="woAT1fgTih" name="Entite" documentation="" x="961" y="765" width="200"
      height="308">
    <attributes xmi:id="yWyKlQvGqU" name="Nom" documentation=""/>
    <attributes xmi:id="uUL3EQ04Op" name="Sigle" documentation=""/>
    <attributes xmi:id="aemWVyCAva" name="Activites" documentation=""/>
    <attributes xmi:id="d4LeuuLwXC" name="Adresse" documentation=""/>
    <attributes xmi:id="xAeIoMTTcr" name="Forme Juridique" documentation=""/>
    <attributes xmi:id="rWCxAAtnhs" name="CA" documentation="" type="NumericalValue"/>
    <attributes xmi:id="zcO6T0kWNI" name="Effectif" documentation="" type="NumericalValue"/>
    <attributes xmi:id="JK6ZfewHSp" name="code NAF" documentation=""/>
    <attributes xmi:id="f5K7qKqwkD" name="Annee de creation" documentation="" type="NumericalValue"/>
    <attributes xmi:id="Kb2EgkIUoM" name="SIRET" documentation="" type="NumericalValue"/>
    <attributes xmi:id="QC2y6FXaS5" name="Capital" documentation="" type="NumericalValue"/>
    <attributes xmi:id="LiPt9bppFE" name="Societe Mere" documentation="" type="Other"/>
  </entities>
  <entities xmi:id="fnirTktsVh" name="Filiere" documentation="" x="441" y="1257" width="200"
      height="55">
    <attributes xmi:id="NkRd3y0ha2" name="Nom" documentation=""/>
  </entities>
  <entities xmi:id="TEexzsSvyI" name="Role" documentation="" x="597" y="764" width="200"
      height="78">
    <attributes xmi:id="VygyRKkMHu" name="Fonction" documentation=""/>
    <attributes xmi:id="cIA9J7xD34" name="Service" documentation=""/>
  </entities>
  <entities xmi:id="ukf6ayXH9x" name="Action" documentation="" x="46" y="921" width="198"
      height="101">
    <attributes xmi:id="duLGX9Krif" name="Date" documentation="" type="TemporalValue"/>
    <attributes xmi:id="xTvGuzXbtW" name="Type" documentation=""/>
    <attributes xmi:id="nPEIE4r4rn" name="Commentaire" documentation=""/>
  </entities>
  <entities xmi:id="7guHOgNEIK" name="Atelier" documentation="" x="1486" y="768" width="200"
      height="113">
    <attributes xmi:id="yaykzPmhtg" name="Nom" documentation=""/>
    <attributes xmi:id="yZEDHrfF2V" name="Date" documentation="" type="TemporalValue"/>
    <attributes xmi:id="zMVvwwH0k8" name="Invitation" documentation=""/>
  </entities>
  <entities xmi:id="eKVaZOtQ8o" name="Liste de Contact" documentation="" x="1261"
      y="1127" width="200" height="55">
    <attributes xmi:id="aGEBOKMw47" name="Type" documentation=""/>
  </entities>
  <entities xmi:id="0JfzyXhDDM" name="Newsletter" documentation="" x="1735" y="994"
      width="303" height="99">
    <attributes xmi:id="bpqzO2Xima" name="Groupe de destinataires" documentation=""/>
  </entities>
  <entities xmi:id="OdwF49GfSM" name="Document" documentation="" x="2452" y="751"
      width="200" height="101">
    <attributes xmi:id="VkSLHzhddP" name="Nom" documentation=""/>
    <attributes xmi:id="auddNpHQTy" name="Type" documentation=""/>
    <attributes xmi:id="K5po4rPTkA" name="Stockage" documentation=""/>
  </entities>
  <entities xmi:id="fkHhRpNdDn" name="Espace" documentation="" x="2587" y="301" width="200"
      height="50"/>
  <entities xmi:id="UI55xfJhzF" name="Regle" documentation="" x="2598" y="512" width="200"
      height="50"/>
  <entities xmi:id="xg47dJx1WW" name="Processus" documentation="" x="2602" y="581"
      width="200" height="50"/>
  <relations xmi:id="rZJvGKqDBU" name="Membres" documentation="">
    <ends object="#4o9UxgVcRa" maxCardinality="-1"/>
    <ends object="#eKVaZOtQ8o" maxCardinality="1"/>
  </relations>
  <relations xmi:id="2UATcMqRvP" name="Filière" documentation="">
    <ends object="#fnirTktsVh" maxCardinality="1"/>
    <ends object="#4o9UxgVcRa" maxCardinality="1"/>
  </relations>
  <relations xmi:id="E2bES1AJ7c" name="Rôle" documentation="">
    <ends object="#4o9UxgVcRa" maxCardinality="-1"/>
    <ends object="#TEexzsSvyI" maxCardinality="-1"/>
  </relations>
  <relations xmi:id="QIwzkZE2rB" name="Actions" documentation="">
    <ends object="#4o9UxgVcRa" maxCardinality="1"/>
    <ends object="#ukf6ayXH9x" maxCardinality="-1"/>
  </relations>
  <relations xmi:id="1VNTolZ6OW" name="Filière" documentation="">
    <ends object="#fnirTktsVh" maxCardinality="1"/>
    <ends object="#woAT1fgTih" maxCardinality="-1"/>
  </relations>
  <relations xmi:id="UiapWhT27l" name="Rôle" documentation="">
    <ends object="#woAT1fgTih" maxCardinality="-1"/>
    <ends object="#TEexzsSvyI" maxCardinality="-1"/>
  </relations>
  <relations xmi:id="2SZEnK2e5T" name="Filière" documentation="">
    <ends object="#fnirTktsVh" maxCardinality="-1"/>
    <ends object="#OdwF49GfSM" maxCardinality="-1"/>
  </relations>
  <relations xmi:id="CD5dSS6LxR" name="" documentation="">
    <ends object="#eKVaZOtQ8o" maxCardinality="1"/>
    <ends object="#7guHOgNEIK" maxCardinality="1"/>
  </relations>
  <relations xmi:id="ZPKvN12dv0" name="Listes de contacts" documentation="">
    <ends object="#eKVaZOtQ8o" maxCardinality="-1"/>
    <ends object="#7guHOgNEIK" maxCardinality="-1"/>
  </relations>
  <relations xmi:id="ssN3b5RI3z" name="Newsletter" documentation="">
    <ends object="#0JfzyXhDDM" maxCardinality="-1"/>
    <ends object="#7guHOgNEIK" maxCardinality="1"/>
  </relations>
  <relations xmi:id="fFTl8OQSCI" name="Liste des inscrits" documentation="">
    <ends object="#eKVaZOtQ8o" maxCardinality="1"/>
    <ends object="#0JfzyXhDDM" maxCardinality="1"/>
  </relations>
</rwm:RequirementsDefinition>
